#!/usr/bin/env python3
"""Append 20 new plant entries to src/data/plants.ts before the closing `] as const;`."""

from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLANTS_TS = ROOT / "src" / "data" / "plants.ts"

# Highest existing id is plant-048.
NEW_PLANTS = [
    {
        "id": "plant-049",
        "slug": "blyxa-japonica",
        "commonName": "Blyxa Japonica",
        "scientificName": "Blyxa japonica",
        "family": "Hydrocharitaceae",
        "origin": "East and Southeast Asia",
        "plantType": "Rosette",
        "position": "Midground",
        "maxHeight": "10–25",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Medium",
        "tempRange": "20–28",
        "phRange": "5.5–7.0",
        "dghRange": "1–10",
        "flowRate": "Low to Medium",
        "difficulty": 3,
        "substrate": "Aquasoil preferred, root tabs in inert substrate",
        "propagation": "Side shoots from the rosette base",
        "careSummary": "A grassy rosette that throws fountain-like blades and flushes bronze-orange under high light. The signature midground plant of the iwagumi style — pairs with hairgrass and Monte Carlo for the classic Japanese stone scape. Wants soft, slightly acidic water to colour up.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Blyxa_japonica",
    },
    {
        "id": "plant-050",
        "slug": "pogostemon-stellatus-octopus",
        "commonName": "Pogostemon Stellatus 'Octopus'",
        "scientificName": "Pogostemon stellatus 'Octopus'",
        "family": "Lamiaceae",
        "origin": "Selectively bred cultivar (Asian parentage)",
        "plantType": "Stem",
        "position": "Background",
        "maxHeight": "30–50",
        "light": "High",
        "co2": "Required",
        "growthRate": "Fast",
        "tempRange": "22–28",
        "phRange": "5.5–7.0",
        "dghRange": "2–10",
        "flowRate": "Medium",
        "difficulty": 3,
        "substrate": "Aquasoil + iron-rich dosing",
        "propagation": "Top cuttings replanted into substrate",
        "careSummary": "The whorled, tentacle-like leaves give this stem plant its octopus nickname. Lime-green in moderate light, flushes lavender-pink at the tips under intense light and lean nitrate. A demanding background plant that rewards a high-tech setup with a spectacular fountain of leaves.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pogostemon",
    },
    {
        "id": "plant-051",
        "slug": "eriocaulon-cinereum",
        "commonName": "Eriocaulon Cinereum",
        "scientificName": "Eriocaulon cinereum",
        "family": "Eriocaulaceae",
        "origin": "Southeast Asia, India",
        "plantType": "Rosette",
        "position": "Midground",
        "maxHeight": "5–10",
        "light": "High",
        "co2": "Required",
        "growthRate": "Slow",
        "tempRange": "22–27",
        "phRange": "5.0–6.8",
        "dghRange": "0–6",
        "flowRate": "Low",
        "difficulty": 4,
        "substrate": "Active aquasoil mandatory",
        "propagation": "Division of mature rosettes",
        "careSummary": "A nano rosette plant with grass-like blades that fan out from a central crown. Picky about water — needs soft, acidic, and CO₂-rich conditions to thrive. Pearls heavily and forms tight green starbursts on the substrate. Single specimens used as accent points in nano scapes.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Eriocaulon_cinereum",
    },
    {
        "id": "plant-052",
        "slug": "rotala-macrandra",
        "commonName": "Rotala Macrandra",
        "scientificName": "Rotala macrandra",
        "family": "Lythraceae",
        "origin": "India",
        "plantType": "Stem",
        "position": "Background",
        "maxHeight": "20–50",
        "light": "High",
        "co2": "Required",
        "growthRate": "Medium",
        "tempRange": "22–28",
        "phRange": "5.5–7.0",
        "dghRange": "2–10",
        "flowRate": "Low to Medium",
        "difficulty": 4,
        "substrate": "Aquasoil + heavy iron and micronutrient dosing",
        "propagation": "Top cuttings",
        "careSummary": "The benchmark red stem plant — intense ruby-red to deep magenta when grown correctly. Brittle leaves shed easily during transport and re-planting, so handle with patience. Demands strong light, CO₂, and a lean nitrate/heavy iron regime to hold colour against the green of the rest of the tank.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Rotala_macrandra",
    },
    {
        "id": "plant-053",
        "slug": "ludwigia-palustris",
        "commonName": "Ludwigia Palustris",
        "scientificName": "Ludwigia palustris",
        "family": "Onagraceae",
        "origin": "Cosmopolitan (Europe, Americas, Asia)",
        "plantType": "Stem",
        "position": "Background",
        "maxHeight": "20–40",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Fast",
        "tempRange": "18–28",
        "phRange": "5.5–8.0",
        "dghRange": "3–15",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Tolerant — inert or active works with root tabs",
        "propagation": "Top cuttings",
        "careSummary": "The classic forgiving red stem plant — easier than macrandra or super red. Pushes orange to deep-red tones under good light without needing soft or acidic water. Sometimes sold as Ludwigia palustris 'Red' or 'Mini'. A reliable first red plant for low-tech and CO₂ tanks alike.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Ludwigia_palustris",
    },
    {
        "id": "plant-054",
        "slug": "ludwigia-arcuata",
        "commonName": "Ludwigia Arcuata",
        "scientificName": "Ludwigia arcuata",
        "family": "Onagraceae",
        "origin": "Southeastern United States",
        "plantType": "Stem",
        "position": "Background to midground",
        "maxHeight": "20–35",
        "light": "High",
        "co2": "Recommended",
        "growthRate": "Medium",
        "tempRange": "20–27",
        "phRange": "5.5–7.5",
        "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Aquasoil + iron dosing",
        "propagation": "Top cuttings",
        "careSummary": "A fine-leaved Ludwigia that flushes deep orange-red at the tops under strong light. Needle-narrow leaves give it a softer, more delicate look than repens or palustris — good for breaking up broad-leaved plants behind it. Trim weekly to thicken into a column rather than a single stem.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Ludwigia_arcuata",
    },
    {
        "id": "plant-055",
        "slug": "riccia-fluitans",
        "commonName": "Riccia Fluitans",
        "scientificName": "Riccia fluitans",
        "family": "Ricciaceae",
        "origin": "Cosmopolitan",
        "plantType": "Floating (or tied to hardscape)",
        "position": "Floating or foreground",
        "maxHeight": "1–3",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Fast",
        "tempRange": "20–28",
        "phRange": "6.0–8.0",
        "dghRange": "1–15",
        "flowRate": "Low",
        "difficulty": 2,
        "substrate": "Not planted — tied to stone or wood, or floated.",
        "propagation": "Fragments — broken pieces grow on",
        "careSummary": "A free-floating liverwort that pearls heavily under CO₂ and bright light — Amano famously tied it to stones with hairnet to make submerged carpets. Will rise to the surface as new growth pulls free; trim and re-attach to maintain a tight submerged form.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Riccia_fluitans",
    },
    {
        "id": "plant-056",
        "slug": "susswassertang",
        "commonName": "Süßwassertang",
        "scientificName": "Lomariopsis lineata",
        "family": "Lomariopsidaceae",
        "origin": "Tropical regions worldwide (uncertain provenance)",
        "plantType": "Epiphyte (fern gametophyte)",
        "position": "Tied to hardscape",
        "maxHeight": "5–15",
        "light": "Low to Medium",
        "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "18–28",
        "phRange": "5.5–7.5",
        "dghRange": "1–15",
        "flowRate": "Low",
        "difficulty": 1,
        "substrate": "Not planted — tied to stone or wood with cotton thread.",
        "propagation": "Pull off clumps and re-tie",
        "careSummary": "Often called \"round pellia\" — a soft, branching fern gametophyte that drapes over rock and wood. Light green, undemanding, tolerates shade and low CO₂ unlike most aquatic plants. The right choice for shaded crevices where mosses look untidy.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Lomariopsis",
    },
    {
        "id": "plant-057",
        "slug": "ammania-gracilis",
        "commonName": "Ammannia Gracilis",
        "scientificName": "Ammannia gracilis",
        "family": "Lythraceae",
        "origin": "West Africa, Senegal to Cameroon",
        "plantType": "Stem",
        "position": "Background",
        "maxHeight": "30–60",
        "light": "High",
        "co2": "Required",
        "growthRate": "Medium",
        "tempRange": "22–28",
        "phRange": "5.5–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 3,
        "substrate": "Aquasoil + iron dosing",
        "propagation": "Top cuttings",
        "careSummary": "Tall background stem with broad, slightly twisted leaves that flush copper-red to violet under high light. Less brittle than Rotala macrandra but with similar colour potential. Reads as a single block of red in the background, useful as a contrast wall behind green stems.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Ammannia_gracilis",
    },
    {
        "id": "plant-058",
        "slug": "myriophyllum-mattogrossense",
        "commonName": "Mato Grosso Milfoil",
        "scientificName": "Myriophyllum mattogrossense",
        "family": "Haloragaceae",
        "origin": "Brazil",
        "plantType": "Stem",
        "position": "Background",
        "maxHeight": "20–50",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Fast",
        "tempRange": "20–28",
        "phRange": "5.5–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Tolerant — aquasoil or inert with root tabs",
        "propagation": "Top cuttings",
        "careSummary": "Fine, feathery foliage in lime to yellow-green — looks like a softer, brighter take on the standard parrot's feather. Adds movement and texture as a backdrop to bolder stem plants. Pearls visibly under CO₂. Trim weekly to encourage side shoots and a fuller bush form.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Myriophyllum",
    },
    {
        "id": "plant-059",
        "slug": "heteranthera-zosterifolia",
        "commonName": "Stargrass",
        "scientificName": "Heteranthera zosterifolia",
        "family": "Pontederiaceae",
        "origin": "Brazil, Bolivia, Paraguay",
        "plantType": "Stem",
        "position": "Background to midground",
        "maxHeight": "20–40",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Fast",
        "tempRange": "20–28",
        "phRange": "5.5–7.5",
        "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Tolerant",
        "propagation": "Top cuttings — also branches readily",
        "careSummary": "A spiky, branching stem with narrow lance-shaped leaves arranged in tight whorls — like an underwater juniper. Branches sideways more than most stems, so trim aggressively to keep it from sprawling into neighbours. Reliable colour: bright green throughout, no red flush to chase.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Heteranthera_zosterifolia",
    },
    {
        "id": "plant-060",
        "slug": "cyperus-helferi",
        "commonName": "Cyperus Helferi",
        "scientificName": "Cyperus helferi",
        "family": "Cyperaceae",
        "origin": "Thailand",
        "plantType": "Rosette",
        "position": "Midground to background",
        "maxHeight": "20–40",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Slow",
        "tempRange": "22–28",
        "phRange": "6.0–7.5",
        "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Aquasoil preferred; root tabs in inert",
        "propagation": "Division of mature clumps",
        "careSummary": "A grass-like rosette of fine, ribbon-thin leaves that arc outward and ripple in flow. Plant in clumps of three to five, spaced to allow each rosette room to fan out. Reads as a soft transition between background stems and lower midground rosettes.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Cyperus_helferi",
    },
    {
        "id": "plant-061",
        "slug": "helanthium-vesuvius",
        "commonName": "Helanthium 'Vesuvius'",
        "scientificName": "Helanthium tenellum 'Vesuvius'",
        "family": "Alismataceae",
        "origin": "Selectively bred cultivar (South American parentage)",
        "plantType": "Rosette",
        "position": "Midground",
        "maxHeight": "10–20",
        "light": "Medium to High",
        "co2": "Optional",
        "growthRate": "Medium",
        "tempRange": "22–28",
        "phRange": "6.0–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Nutrient-rich substrate + root tabs",
        "propagation": "Runners — sends out new plantlets",
        "careSummary": "A twisted-leaf cultivar of the chain sword — every blade spirals as it grows, giving the rosette a sculptural quality you don't get from straight-leaved species. Sends runners across the substrate and forms a midground colony over months. Tolerant of low-tech setups.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Helanthium_tenellum",
    },
    {
        "id": "plant-062",
        "slug": "water-lettuce",
        "commonName": "Water Lettuce",
        "scientificName": "Pistia stratiotes",
        "family": "Araceae",
        "origin": "Tropics worldwide",
        "plantType": "Floating",
        "position": "Floating",
        "maxHeight": "5–15",
        "light": "Medium to High",
        "co2": "Not required",
        "growthRate": "Very fast",
        "tempRange": "20–30",
        "phRange": "6.0–8.0",
        "dghRange": "1–15",
        "flowRate": "Low (still water)",
        "difficulty": 1,
        "substrate": "Floating — no substrate",
        "propagation": "Daughter rosettes from runners",
        "careSummary": "A large floating rosette of pale-green velvety leaves that trails long feathery roots into the water column. Excellent nitrate sponge and surface shade for shy fish like sparkling gourami. Banned as an invasive in several jurisdictions — check local regulations before introducing.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pistia",
    },
    {
        "id": "plant-063",
        "slug": "cryptocoryne-walkeri",
        "commonName": "Cryptocoryne Walkeri",
        "scientificName": "Cryptocoryne walkeri",
        "family": "Araceae",
        "origin": "Sri Lanka",
        "plantType": "Rosette",
        "position": "Midground",
        "maxHeight": "10–25",
        "light": "Low to Medium",
        "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "22–28",
        "phRange": "6.0–8.0",
        "dghRange": "3–15",
        "flowRate": "Low",
        "difficulty": 1,
        "substrate": "Nutrient-rich substrate + root tabs",
        "propagation": "Runners from the base",
        "careSummary": "An undemanding crypt with olive-green to bronze leaves that ripple at the edges. Will melt on transplant — the leaves dissolve then regrow from the rhizome over two to three weeks. Once established, sends runners and slowly forms a midground colony. Tolerates harder, more alkaline water than wendtii.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Cryptocoryne_walkeri",
    },
    {
        "id": "plant-064",
        "slug": "lindernia-rotundifolia",
        "commonName": "Lindernia Rotundifolia",
        "scientificName": "Lindernia rotundifolia",
        "family": "Linderniaceae",
        "origin": "India and Sri Lanka",
        "plantType": "Stem",
        "position": "Midground",
        "maxHeight": "10–25",
        "light": "Medium",
        "co2": "Optional",
        "growthRate": "Medium",
        "tempRange": "22–28",
        "phRange": "5.5–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Tolerant",
        "propagation": "Top cuttings",
        "careSummary": "Sometimes sold as Variegated Lindernia — bright green rounded leaves veined in cream-white. Beginner-friendly midground stem that tolerates a wide range of light and water parameters. Pinch the tops to encourage bushy side growth instead of a single-stem column.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Lindernia_rotundifolia",
    },
    {
        "id": "plant-065",
        "slug": "java-fern-narrow",
        "commonName": "Narrow Leaf Java Fern",
        "scientificName": "Microsorum pteropus 'Narrow Leaf'",
        "family": "Polypodiaceae",
        "origin": "Southeast Asia",
        "plantType": "Epiphyte",
        "position": "Midground to background",
        "maxHeight": "15–35",
        "light": "Low to Medium",
        "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "20–28",
        "phRange": "5.5–7.8",
        "dghRange": "1–15",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Not planted — tied to stone or wood.",
        "propagation": "Daughter plants on leaf tips, or rhizome division",
        "careSummary": "The slimmer cultivar of the classic java fern — leaves stay below 1.5 cm wide, giving the plant a more delicate, grass-like silhouette compared to the regular form. Same care as the standard species: low light, no substrate needed, never bury the rhizome.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Microsorum_pteropus",
    },
    {
        "id": "plant-066",
        "slug": "anubias-petite",
        "commonName": "Anubias Barteri 'Petite'",
        "scientificName": "Anubias barteri var. nana 'Petite'",
        "family": "Araceae",
        "origin": "Selectively bred cultivar (West African parentage)",
        "plantType": "Epiphyte",
        "position": "Foreground to midground",
        "maxHeight": "3–7",
        "light": "Low to Medium",
        "co2": "Optional",
        "growthRate": "Very slow",
        "tempRange": "22–28",
        "phRange": "5.5–8.0",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Not planted — tied to stone or wood.",
        "propagation": "Rhizome division",
        "careSummary": "The smallest anubias variety, with leaves under 2 cm — the nano-tank equivalent of standard anubias nana. Tucks into wood crevices and on small stones where bigger anubias would dominate the scape. Same care: rhizome above the substrate or it rots; rinse algae off leaves regularly.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Anubias_barteri",
    },
    {
        "id": "plant-067",
        "slug": "echinodorus-red-flame",
        "commonName": "Echinodorus 'Red Flame'",
        "scientificName": "Echinodorus 'Red Flame'",
        "family": "Alismataceae",
        "origin": "Selectively bred cultivar (South American parentage)",
        "plantType": "Rosette",
        "position": "Background",
        "maxHeight": "25–50",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Medium",
        "tempRange": "22–28",
        "phRange": "5.5–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Nutrient-rich substrate + root tabs",
        "propagation": "Adventitious plantlets on flower stalks",
        "careSummary": "A large background sword cultivar with deep green leaves splashed in red and copper flecks. Reads as a focal-point specimen plant rather than a mass — one or two crowns are enough in a 200 L tank. Hungry feeder, root tabs are non-optional in inert substrate.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Echinodorus",
    },
    {
        "id": "plant-068",
        "slug": "eleocharis-vivipara",
        "commonName": "Umbrella Hairgrass",
        "scientificName": "Eleocharis vivipara",
        "family": "Cyperaceae",
        "origin": "Southeastern United States",
        "plantType": "Rosette",
        "position": "Midground to background",
        "maxHeight": "20–50",
        "light": "Medium to High",
        "co2": "Recommended",
        "growthRate": "Medium",
        "tempRange": "20–28",
        "phRange": "5.5–7.5",
        "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Aquasoil preferred; root tabs in inert",
        "propagation": "Daughter plantlets at the leaf tips",
        "careSummary": "A taller hairgrass that produces baby plantlets at the tips of mature blades — they bend over, root into the substrate, and form new clumps in cascading layers. Adds vertical motion to midground scapes that ordinary dwarf hairgrass can't provide.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Eleocharis_vivipara",
    },
]


TEMPLATE = """  {{
    id: "{id}",
    slug: "{slug}",
    category: "plants",
    commonName: "{commonName}",
    scientificName: "{scientificName}",
    family: "{family}",
    origin: "{origin}",
    plantType: "{plantType}",
    position: "{position}",
    maxHeight: "{maxHeight}",
    light: "{light}",
    co2: "{co2}",
    growthRate: "{growthRate}",
    tempRange: "{tempRange}",
    phRange: "{phRange}",
    dghRange: "{dghRange}",
    flowRate: "{flowRate}",
    difficulty: {difficulty},
    substrate: "{substrate}",
    propagation: "{propagation}",
    careSummary: "{careSummary}",
    imageSourceUrl: "{imageSourceUrl}",
    imageLicenseHint: "Commons (mostly CC-BY-SA)",
  }},"""


def main() -> None:
    src = PLANTS_TS.read_text(encoding="utf-8")
    if "] as const;" not in src:
        raise SystemExit("Could not find closing `] as const;` in plants.ts")

    rendered = []
    for entry in NEW_PLANTS:
        safe = {k: (v.replace('"', '\\"') if isinstance(v, str) else v) for k, v in entry.items()}
        rendered.append(TEMPLATE.format(**safe))
    block = "\n".join(rendered) + "\n"

    new_src = src.replace("] as const;", block + "] as const;")
    PLANTS_TS.write_text(new_src, encoding="utf-8")
    print(f"OK — appended {len(NEW_PLANTS)} plants to {PLANTS_TS}")


if __name__ == "__main__":
    main()
