#!/usr/bin/env python3
"""Append 15 new plant entries (session 07)."""

from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLANTS_TS = ROOT / "src" / "data" / "plants.ts"

NEW_PLANTS = [
    {
        "id": "plant-069", "slug": "limnophila-aromatica",
        "commonName": "Limnophila Aromatica", "scientificName": "Limnophila aromatica",
        "family": "Plantaginaceae", "origin": "Southeast Asia",
        "plantType": "Stem", "position": "Background",
        "maxHeight": "25–50", "light": "High", "co2": "Required",
        "growthRate": "Medium",
        "tempRange": "22–28", "phRange": "5.5–7.5", "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 3,
        "substrate": "Aquasoil + iron-rich dosing",
        "propagation": "Top cuttings",
        "careSummary": "A serrated-leaf stem plant that flushes deep purple-red on the underside of each leaf when grown under high light. Aromatic when crushed (it is the Vietnamese herb 'rice paddy herb' grown emersed). Trim weekly to encourage side shoots.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Limnophila_aromatica",
    },
    {
        "id": "plant-070", "slug": "bacopa-salzmannii",
        "commonName": "Purple Bacopa", "scientificName": "Bacopa salzmannii",
        "family": "Plantaginaceae", "origin": "South America",
        "plantType": "Stem", "position": "Background to midground",
        "maxHeight": "20–35", "light": "Medium to High", "co2": "Recommended",
        "growthRate": "Medium",
        "tempRange": "22–28", "phRange": "5.5–7.5", "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Aquasoil preferred; tolerates inert with root tabs",
        "propagation": "Top cuttings",
        "careSummary": "The purple cousin of Bacopa caroliniana, with darker stems and a deep violet-purple flush at the tips under high light. Slower-growing than other bacopas, which makes it easier to keep tidy in the midground.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Bacopa",
    },
    {
        "id": "plant-071", "slug": "hornwort",
        "commonName": "Hornwort", "scientificName": "Ceratophyllum demersum",
        "family": "Ceratophyllaceae", "origin": "Cosmopolitan",
        "plantType": "Stem (rootless)", "position": "Background or floating",
        "maxHeight": "30–100", "light": "Low to High", "co2": "Not required",
        "growthRate": "Very fast",
        "tempRange": "15–28", "phRange": "6.0–8.0", "dghRange": "5–25",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "None required (rootless, can float or be weighted into substrate)",
        "propagation": "Snap and re-plant any segment",
        "careSummary": "A rootless stem plant that absorbs nutrients across its whole body. Grows fast in any conditions, the right algae-suppressor for new tank setups. Sheds needles when first introduced (light shock); recovers within two weeks.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Ceratophyllum_demersum",
    },
    {
        "id": "plant-072", "slug": "marsilea-quadrifolia",
        "commonName": "Four-Leaf Clover", "scientificName": "Marsilea quadrifolia",
        "family": "Marsileaceae", "origin": "Europe, Asia, naturalised in North America",
        "plantType": "Carpet (fern)", "position": "Foreground",
        "maxHeight": "3–8", "light": "Medium to High", "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "18–28", "phRange": "6.0–7.5", "dghRange": "2–15",
        "flowRate": "Low",
        "difficulty": 2,
        "substrate": "Aquasoil preferred; root tabs in inert substrate",
        "propagation": "Runners — sends out plantlets along the substrate",
        "careSummary": "An aquatic fern that produces tiny four-leaf-clover fronds when submerged. Slower than Marsilea hirsuta and gives a more delicate, almost clover-like carpet. Tolerates much cooler water than tropical carpet plants.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Marsilea_quadrifolia",
    },
    {
        "id": "plant-073", "slug": "aponogeton-madagascariensis",
        "commonName": "Madagascar Lace Plant", "scientificName": "Aponogeton madagascariensis",
        "family": "Aponogetonaceae", "origin": "Madagascar",
        "plantType": "Bulb", "position": "Midground to background",
        "maxHeight": "30–60", "light": "Medium", "co2": "Recommended",
        "growthRate": "Medium",
        "tempRange": "20–26", "phRange": "5.5–7.5", "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 4,
        "substrate": "Nutrient-rich substrate + root tabs; bulb sits half-buried",
        "propagation": "Bulb division or seed",
        "careSummary": "Iconic lace-pattern leaves — like submerged stained glass. Each leaf is a skeleton of cross-veins with no membrane between them. Needs a cool, soft, dim, slightly current-driven tank. The species periodically goes dormant; do not throw out the bulb when leaves die back.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Aponogeton_madagascariensis",
    },
    {
        "id": "plant-074", "slug": "crinum-calamistratum",
        "commonName": "Crinum Calamistratum", "scientificName": "Crinum calamistratum",
        "family": "Amaryllidaceae", "origin": "West Africa",
        "plantType": "Bulb", "position": "Background (specimen)",
        "maxHeight": "60–120", "light": "Medium", "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "22–28", "phRange": "6.5–8.0", "dghRange": "5–20",
        "flowRate": "Medium",
        "difficulty": 2,
        "substrate": "Nutrient-rich + root tabs; bulb sits above the substrate",
        "propagation": "Side bulbs",
        "careSummary": "Long, narrow, deeply crinkled dark-green leaves that grow from a large bulb. The specimen plant for tall African biotopes and Tanganyikan-themed tanks. Tolerates hard, alkaline water that kills most South American plants.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Crinum_calamistratum",
    },
    {
        "id": "plant-075", "slug": "pogostemon-erectus",
        "commonName": "Pogostemon Erectus", "scientificName": "Pogostemon erectus",
        "family": "Lamiaceae", "origin": "India",
        "plantType": "Stem", "position": "Background to midground",
        "maxHeight": "20–40", "light": "Medium to High", "co2": "Recommended",
        "growthRate": "Fast",
        "tempRange": "22–28", "phRange": "5.5–7.5", "dghRange": "2–12",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Aquasoil preferred",
        "propagation": "Top cuttings",
        "careSummary": "Stiff, vertical stems lined with fine needle-like green leaves arranged in dense whorls — reads like an underwater conifer or a more upright juniper. Grows in tight bunches, perfect for filling background gaps with structure.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pogostemon",
    },
    {
        "id": "plant-076", "slug": "guppy-grass",
        "commonName": "Guppy Grass", "scientificName": "Najas guadalupensis",
        "family": "Hydrocharitaceae", "origin": "Americas (Caribbean and Gulf)",
        "plantType": "Stem (rootless)", "position": "Background or floating",
        "maxHeight": "30–60", "light": "Low to High", "co2": "Not required",
        "growthRate": "Very fast",
        "tempRange": "15–28", "phRange": "6.0–8.0", "dghRange": "3–20",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Optional — grows free-floating or weighted in substrate",
        "propagation": "Any broken segment grows on",
        "careSummary": "A fast-growing, fine-leaved stem that thrives floating or anchored. The breeder's secret weapon: shrimplets and fry hide in its dense foliage, and it strips nitrate from new tanks fast. Snaps easily during gravel-vac; replant the fragments.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Najas_guadalupensis",
    },
    {
        "id": "plant-077", "slug": "anubias-coffeefolia",
        "commonName": "Anubias Coffeefolia", "scientificName": "Anubias barteri 'Coffeefolia'",
        "family": "Araceae", "origin": "Cultivar (West African parentage)",
        "plantType": "Epiphyte", "position": "Midground",
        "maxHeight": "10–20", "light": "Low to Medium", "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "22–28", "phRange": "5.5–8.0", "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Not planted — tied to stone or wood with thread.",
        "propagation": "Rhizome division",
        "careSummary": "Distinctive bumpy, ridged leaves that emerge bronze-red before darkening to deep green. Like the standard Anubias barteri but with a sculptural leaf texture. Care identical: rhizome above the substrate, low light fine, slow grower.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Anubias_barteri",
    },
    {
        "id": "plant-078", "slug": "anubias-hastifolia",
        "commonName": "Spear-leaf Anubias", "scientificName": "Anubias hastifolia",
        "family": "Araceae", "origin": "West and Central Africa",
        "plantType": "Epiphyte", "position": "Midground to background",
        "maxHeight": "20–40", "light": "Low to Medium", "co2": "Optional",
        "growthRate": "Slow",
        "tempRange": "22–28", "phRange": "5.5–7.5", "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "difficulty": 2,
        "substrate": "Not planted — tied to large rocks or wood structures.",
        "propagation": "Rhizome division",
        "careSummary": "A large, taller anubias with arrow-shaped (hastate) leaves and a tropical-jungle silhouette. Best used as a single specimen on a large piece of driftwood. Holds size — won't disappear behind broad swords.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Anubias_hastifolia",
    },
    {
        "id": "plant-079", "slug": "echinodorus-ozelot",
        "commonName": "Echinodorus 'Ozelot'", "scientificName": "Echinodorus 'Ozelot'",
        "family": "Alismataceae", "origin": "Cultivar (South American parentage)",
        "plantType": "Rosette", "position": "Background",
        "maxHeight": "25–50", "light": "Medium", "co2": "Optional",
        "growthRate": "Medium",
        "tempRange": "22–28", "phRange": "6.0–7.5", "dghRange": "5–20",
        "flowRate": "Low to Medium",
        "difficulty": 1,
        "substrate": "Nutrient-rich substrate + root tabs",
        "propagation": "Adventitious plantlets on flower stalks",
        "careSummary": "A sword with bright leopard-spotted leaves — green ground splashed with crimson dots that intensify under good light. Hardier than 'Red Flame', easier than most red-flushing swords. A single specimen anchors the background of a 200 L tank.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Echinodorus",
    },
    {
        "id": "plant-080", "slug": "vallisneria-americana",
        "commonName": "Jungle Vallisneria", "scientificName": "Vallisneria americana",
        "family": "Hydrocharitaceae", "origin": "North and Central America",
        "plantType": "Rosette", "position": "Background",
        "maxHeight": "50–120", "light": "Medium", "co2": "Not required",
        "growthRate": "Fast",
        "tempRange": "18–28", "phRange": "6.5–8.0", "dghRange": "5–25",
        "flowRate": "Medium",
        "difficulty": 1,
        "substrate": "Nutrient-rich + root tabs in inert substrate",
        "propagation": "Runners — sends plantlets across the substrate",
        "careSummary": "Wider, taller, hardier than Vallisneria spiralis — leaves can hit a metre in mature tanks and easily overflow on the surface. The right background plant for tall tanks (60 cm+). Tolerates harder, more alkaline water than most.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Vallisneria_americana",
    },
    {
        "id": "plant-081", "slug": "eichhornia-diversifolia",
        "commonName": "Eichhornia Diversifolia", "scientificName": "Eichhornia diversifolia",
        "family": "Pontederiaceae", "origin": "South America",
        "plantType": "Stem", "position": "Background",
        "maxHeight": "30–50", "light": "High", "co2": "Required",
        "growthRate": "Medium",
        "tempRange": "22–28", "phRange": "5.5–7.0", "dghRange": "1–8",
        "flowRate": "Low to Medium",
        "difficulty": 4,
        "substrate": "Aquasoil mandatory; very lean nitrate dosing",
        "propagation": "Top cuttings",
        "careSummary": "An advanced soft-water stem with delicate fern-like foliage that flushes purple-red under bright light. Demanding: needs very soft, slightly acidic water and lean nitrate or it browns and dissolves. The reward is a unique cloud-like silhouette unlike any other stem plant.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Eichhornia",
    },
    {
        "id": "plant-082", "slug": "taiwan-moss-lily",
        "commonName": "Taiwan Moss Lily", "scientificName": "Nymphoides hydrophylla 'Taiwan'",
        "family": "Menyanthaceae", "origin": "Cultivar (Asian parentage)",
        "plantType": "Rosette", "position": "Midground",
        "maxHeight": "10–25", "light": "Medium to High", "co2": "Optional",
        "growthRate": "Medium",
        "tempRange": "22–28", "phRange": "6.0–7.5", "dghRange": "5–15",
        "flowRate": "Low",
        "difficulty": 2,
        "substrate": "Nutrient-rich substrate + root tabs",
        "propagation": "Plantlets from emergent leaves",
        "careSummary": "A miniature rhizome lily that forms a compact bouquet of bright-green spade-shaped leaves. Send up surface leaves and small white flowers when given the chance. Trim emergent growth to keep it as a submerged midground feature.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Nymphoides",
    },
    {
        "id": "plant-083", "slug": "sagittaria-platyphylla",
        "commonName": "Giant Sagittaria", "scientificName": "Sagittaria platyphylla",
        "family": "Alismataceae", "origin": "Southeastern United States",
        "plantType": "Rosette", "position": "Background to midground",
        "maxHeight": "20–50", "light": "Medium to High", "co2": "Not required",
        "growthRate": "Medium",
        "tempRange": "18–28", "phRange": "6.5–8.0", "dghRange": "5–20",
        "flowRate": "Medium",
        "difficulty": 1,
        "substrate": "Nutrient-rich + root tabs",
        "propagation": "Runners",
        "careSummary": "Broader, taller, more robust than Sagittaria subulata. Looks like a heavyweight Vallisneria with the same emerald-green colour but more substantial blades. Tolerates hard, alkaline tap water — the right background plant for African Rift biotopes that exclude most stems.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Sagittaria_platyphylla",
    },
]


TEMPLATE = """  {{
    id: "{id}",
    slug: "{slug}",
    category: "plants",
    commonName: "{commonName}",
    scientificName: "{scientificName}",
    family: "{family}",
    origin: "{origin}",
    plantType: "{plantType}",
    position: "{position}",
    maxHeight: "{maxHeight}",
    light: "{light}",
    co2: "{co2}",
    growthRate: "{growthRate}",
    tempRange: "{tempRange}",
    phRange: "{phRange}",
    dghRange: "{dghRange}",
    flowRate: "{flowRate}",
    difficulty: {difficulty},
    substrate: "{substrate}",
    propagation: "{propagation}",
    careSummary: "{careSummary}",
    imageSourceUrl: "{imageSourceUrl}",
    imageLicenseHint: "Commons (mostly CC-BY-SA)",
  }},"""


def main() -> None:
    src = PLANTS_TS.read_text(encoding="utf-8")
    if "] as const;" not in src:
        raise SystemExit("Could not find closing `] as const;`")
    rendered = []
    for entry in NEW_PLANTS:
        safe = {k: (v.replace('"', '\\"') if isinstance(v, str) else v) for k, v in entry.items()}
        rendered.append(TEMPLATE.format(**safe))
    block = "\n".join(rendered) + "\n"
    PLANTS_TS.write_text(src.replace("] as const;", block + "] as const;"), encoding="utf-8")
    print(f"OK — appended {len(NEW_PLANTS)} plants")


if __name__ == "__main__":
    main()
