#!/usr/bin/env python3
"""Append 15 new fish entries (session 07)."""

from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FISH_TS = ROOT / "src" / "data" / "fish.ts"

NEW_FISH = [
    {
        "id": "fish-078", "slug": "pearl-danio",
        "commonName": "Pearl Danio", "scientificName": "Danio albolineatus",
        "family": "Cyprinidae", "origin": "Myanmar, Thailand, Sumatra",
        "adultSize": "5–6 cm", "minTankSize": "75 L",
        "waterColumn": "Mid to top", "temperament": "Peaceful (active)",
        "schooling": "Yes", "minGroupSize": 8,
        "diet": "Omnivore",
        "feedingNotes": "Flake, micro pellet, frozen daphnia and bloodworm.",
        "tempRange": "20–26", "phRange": "6.0–7.5", "dghRange": "2–15",
        "flowRate": "Medium", "lifespan": "5–7",
        "difficulty": 1, "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "A pearlescent silver-pink schooler with iridescent flanks. Holds tighter shoals than zebra danios and is calmer at the surface. The right danio for nano communities where zebra danios are too rambunctious.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pearl_danio",
    },
    {
        "id": "fish-079", "slug": "buenos-aires-tetra",
        "commonName": "Buenos Aires Tetra", "scientificName": "Hyphessobrycon anisitsi",
        "family": "Characidae", "origin": "Paraguay, Uruguay, southern Brazil",
        "adultSize": "7–10 cm", "minTankSize": "150 L",
        "waterColumn": "Mid", "temperament": "Semi-aggressive (plant-eater)",
        "schooling": "Yes", "minGroupSize": 8,
        "diet": "Omnivore (heavy plant-grazer)",
        "feedingNotes": "Flake, pellet, blanched veg, frozen and live foods.",
        "tempRange": "18–28", "phRange": "6.0–8.0", "dghRange": "5–20",
        "flowRate": "Medium to high", "lifespan": "5–7",
        "difficulty": 1, "plantSafe": "No (will defoliate soft plants)",
        "shrimpSafe": "No",
        "breedingDifficulty": "Easy",
        "rarity": 2,
        "careSummary": "Hardy, active, and an indiscriminate plant-eater — keep it with hardscape-only tanks, tough plants like Anubias and java fern, or wild-caught planted setups that can take the abuse. Tolerates cooler temperatures than most South American tetras.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Hyphessobrycon_anisitsi",
    },
    {
        "id": "fish-080", "slug": "black-molly",
        "commonName": "Black Molly", "scientificName": "Poecilia sphenops",
        "family": "Poeciliidae", "origin": "Central America (selectively bred)",
        "adultSize": "8–12 cm", "minTankSize": "100 L",
        "waterColumn": "All", "temperament": "Peaceful",
        "schooling": "Loose group", "minGroupSize": 4,
        "diet": "Omnivore (vegetarian-leaning)",
        "feedingNotes": "Flake, blanched veg, algae wafer, frozen daphnia. High-veg diet improves colour.",
        "tempRange": "24–28", "phRange": "7.0–8.5", "dghRange": "10–25",
        "flowRate": "Low to Medium", "lifespan": "3–5",
        "difficulty": 1, "plantSafe": "Yes (mild grazing)",
        "shrimpSafe": "Adults only (eats shrimplets)",
        "breedingDifficulty": "Very easy",
        "rarity": 1,
        "careSummary": "The all-black livebearer that thrives in hard, alkaline tap water — the opposite chemistry of South American soft-water tanks. Tolerates and even prefers a teaspoon of aquarium salt per 10 L. Females drop fry every 4–6 weeks.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Poecilia_sphenops",
    },
    {
        "id": "fish-081", "slug": "common-pleco",
        "commonName": "Common Pleco", "scientificName": "Pterygoplichthys pardalis",
        "family": "Loricariidae", "origin": "Amazon basin",
        "adultSize": "40–50 cm", "minTankSize": "450 L",
        "waterColumn": "Bottom",
        "temperament": "Peaceful (becomes territorial with age)",
        "schooling": "No", "minGroupSize": 1,
        "diet": "Omnivore (vegetarian-leaning)",
        "feedingNotes": "Algae wafer, blanched veg (zucchini, cucumber), driftwood, occasional protein.",
        "tempRange": "22–28", "phRange": "6.5–8.0", "dghRange": "5–20",
        "flowRate": "Medium to high", "lifespan": "15–20",
        "difficulty": 2, "plantSafe": "No (uproots and rasps soft plants)",
        "shrimpSafe": "Adults only",
        "breedingDifficulty": "Very hard",
        "rarity": 1,
        "careSummary": "Often sold as a 5 cm juvenile that grows into a 40 cm tank-buster within 3 years. Most home tanks cannot house an adult — buy only if a 450 L+ tank is genuinely available. For smaller setups, clown pleco or bristlenose are the right fit.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pterygoplichthys_pardalis",
    },
    {
        "id": "fish-082", "slug": "peacock-gudgeon",
        "commonName": "Peacock Gudgeon", "scientificName": "Tateurndina ocellicauda",
        "family": "Eleotridae", "origin": "Papua New Guinea",
        "adultSize": "5–7 cm", "minTankSize": "60 L",
        "waterColumn": "Mid to bottom",
        "temperament": "Peaceful",
        "schooling": "No (loose group)", "minGroupSize": 1,
        "diet": "Carnivore",
        "feedingNotes": "Frozen bloodworm, daphnia, baby brine shrimp. Often refuses dry food initially.",
        "tempRange": "22–26", "phRange": "6.5–7.5", "dghRange": "5–15",
        "flowRate": "Low to Medium", "lifespan": "4–5",
        "difficulty": 2, "plantSafe": "Yes",
        "shrimpSafe": "Adults only (eats shrimplets)",
        "breedingDifficulty": "Medium (cave spawner, male tends)",
        "rarity": 3,
        "careSummary": "A nano centrepiece with electric-blue and pink-red bands, plus a black tail spot edged in gold. Hovers in mid-water like a tiny dwarf cichlid. Male tends the eggs in a cave. Excellent for densely-planted 60 L setups.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Peacock_gudgeon",
    },
    {
        "id": "fish-083", "slug": "apistogramma-borellii",
        "commonName": "Umbrella Cichlid", "scientificName": "Apistogramma borellii",
        "family": "Cichlidae", "origin": "Paraguay and southern Brazil",
        "adultSize": "5–7 cm", "minTankSize": "75 L",
        "waterColumn": "Bottom to mid",
        "temperament": "Peaceful (mild for an apisto)",
        "schooling": "Pair or harem", "minGroupSize": 1,
        "diet": "Carnivore",
        "feedingNotes": "Frozen bloodworm, brine shrimp, daphnia, micro pellet. Live food triggers breeding colour.",
        "tempRange": "20–26", "phRange": "6.0–7.5", "dghRange": "1–12",
        "flowRate": "Low", "lifespan": "3–5",
        "difficulty": 2, "plantSafe": "Yes",
        "shrimpSafe": "Adults only",
        "breedingDifficulty": "Medium (cave spawner)",
        "rarity": 3,
        "careSummary": "Cooler-water apisto with yellow flanks and a finnage that fans into an umbrella in display. More tolerant of pH and temperature variation than cacatuoides or agassizii, the right starter apisto. Female tends eggs in a cave.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Apistogramma_borellii",
    },
    {
        "id": "fish-084", "slug": "keyhole-cichlid",
        "commonName": "Keyhole Cichlid", "scientificName": "Cleithracara maronii",
        "family": "Cichlidae", "origin": "Northern South America (Orinoco, Guianas)",
        "adultSize": "10–12 cm", "minTankSize": "150 L",
        "waterColumn": "Mid to bottom",
        "temperament": "Peaceful (one of the most peaceful cichlids)",
        "schooling": "Pair", "minGroupSize": 2,
        "diet": "Omnivore",
        "feedingNotes": "Cichlid pellet, frozen bloodworm and brine shrimp, occasional veg.",
        "tempRange": "22–28", "phRange": "6.0–7.5", "dghRange": "5–18",
        "flowRate": "Low to Medium", "lifespan": "8–12",
        "difficulty": 2, "plantSafe": "Yes",
        "shrimpSafe": "Adults only",
        "breedingDifficulty": "Easy (substrate spawner, both parents tend)",
        "rarity": 3,
        "careSummary": "Named for the black keyhole-shaped mark on each flank. Famously the most peaceful South American cichlid, will live with tetras, rasboras, and corydoras without bullying. Pair-bonds for life and both parents fan eggs.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Keyhole_cichlid",
    },
    {
        "id": "fish-085", "slug": "discus",
        "commonName": "Discus", "scientificName": "Symphysodon aequifasciatus",
        "family": "Cichlidae", "origin": "Amazon basin",
        "adultSize": "15–20 cm", "minTankSize": "300 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful (shy)",
        "schooling": "Yes", "minGroupSize": 6,
        "diet": "Carnivore",
        "feedingNotes": "Beef heart mix, frozen bloodworm, blackworm, discus pellets. Multiple small feeds daily.",
        "tempRange": "28–31", "phRange": "5.5–7.0", "dghRange": "1–8",
        "flowRate": "Low", "lifespan": "10–15",
        "difficulty": 4, "plantSafe": "Yes",
        "shrimpSafe": "Adults only",
        "breedingDifficulty": "Hard (pair forms naturally, fry feed on parent slime coat)",
        "rarity": 3,
        "careSummary": "The icon of South American aquariums. Requires warmer water (28–31 °C), soft and slightly acidic chemistry, and large daily water changes — most planted tanks cannot meet all three. A 300 L tank, a group of 6, and a dedicated keeper are non-negotiable.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Symphysodon_aequifasciatus",
    },
    {
        "id": "fish-086", "slug": "three-spot-gourami",
        "commonName": "Three-spot Gourami", "scientificName": "Trichopodus trichopterus",
        "family": "Osphronemidae", "origin": "Southeast Asia",
        "adultSize": "10–15 cm", "minTankSize": "150 L",
        "waterColumn": "Mid to top",
        "temperament": "Semi-aggressive (males territorial)",
        "schooling": "No (single male or harem)", "minGroupSize": 1,
        "diet": "Omnivore",
        "feedingNotes": "Pellet, flake, frozen bloodworm, blanched veg.",
        "tempRange": "22–28", "phRange": "6.0–8.0", "dghRange": "5–20",
        "flowRate": "Low to Medium", "lifespan": "5–8",
        "difficulty": 1, "plantSafe": "Yes",
        "shrimpSafe": "Adults only (eats shrimplets)",
        "breedingDifficulty": "Easy (bubble-nest builder)",
        "rarity": 2,
        "careSummary": "Hardy, beginner-friendly gourami sold in blue, gold, opaline, and lavender colour morphs. Males can be aggressive toward each other and toward smaller surface-dwellers, never keep multiple males together. A 150 L tank with floating plants suits a single male and 3–4 females.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Three_spot_gourami",
    },
    {
        "id": "fish-087", "slug": "kissing-gourami",
        "commonName": "Kissing Gourami", "scientificName": "Helostoma temminckii",
        "family": "Helostomatidae", "origin": "Southeast Asia",
        "adultSize": "20–30 cm", "minTankSize": "300 L",
        "waterColumn": "All",
        "temperament": "Semi-aggressive (the kiss is a dominance display)",
        "schooling": "No", "minGroupSize": 1,
        "diet": "Omnivore (filter-feeder leaning)",
        "feedingNotes": "Pellet, flake, blanched veg, occasional frozen food. Filter-feeds on algae and biofilm.",
        "tempRange": "22–28", "phRange": "6.0–8.0", "dghRange": "5–20",
        "flowRate": "Low to Medium", "lifespan": "10–15",
        "difficulty": 2, "plantSafe": "No (grazes algae and soft plants)",
        "shrimpSafe": "No",
        "breedingDifficulty": "Hard",
        "rarity": 2,
        "careSummary": "The pink kissing gourami of pet-shop folklore. Grows much larger than most buyers expect — 25 cm is typical. The 'kiss' is two males locking jaws as a dominance contest, not affection. Needs a large tank with strong filtration.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Kissing_gourami",
    },
    {
        "id": "fish-088", "slug": "false-julii-cory",
        "commonName": "False Julii Cory", "scientificName": "Corydoras trilineatus",
        "family": "Callichthyidae", "origin": "Upper Amazon",
        "adultSize": "5–6 cm", "minTankSize": "75 L",
        "waterColumn": "Bottom",
        "temperament": "Peaceful",
        "schooling": "Yes", "minGroupSize": 6,
        "diet": "Omnivore",
        "feedingNotes": "Sinking pellet, frozen bloodworm and brine shrimp, scavenges leftovers.",
        "tempRange": "22–26", "phRange": "6.0–7.5", "dghRange": "2–15",
        "flowRate": "Medium", "lifespan": "5–7",
        "difficulty": 1, "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "Almost always sold under the name 'Julii Cory' — true *Corydoras julii* is rare in the trade. The reticulated pattern is finer than *C. julii* (a network rather than spots). Hardy, sand substrate is kinder to barbels than gravel.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Corydoras_trilineatus",
    },
    {
        "id": "fish-089", "slug": "salt-and-pepper-cory",
        "commonName": "Salt and Pepper Cory", "scientificName": "Corydoras habrosus",
        "family": "Callichthyidae", "origin": "Venezuela and Colombia",
        "adultSize": "2.5–3.5 cm", "minTankSize": "45 L",
        "waterColumn": "Bottom",
        "temperament": "Peaceful",
        "schooling": "Yes", "minGroupSize": 8,
        "diet": "Omnivore",
        "feedingNotes": "Crushed sinking pellet, baby brine shrimp, micro worms, finely crushed flake.",
        "tempRange": "22–26", "phRange": "6.0–7.5", "dghRange": "2–12",
        "flowRate": "Low to Medium", "lifespan": "4–6",
        "difficulty": 2, "plantSafe": "Yes",
        "shrimpSafe": "Yes",
        "breedingDifficulty": "Hard",
        "rarity": 3,
        "careSummary": "A dwarf cory smaller than the pygmy — under 3.5 cm fully grown. The black-and-white peppered pattern reads well against sand substrate. Mid-water swimmer like the pygmy cory, not bottom-bound. Excellent for shrimp tanks because they are too small to eat adult shrimp.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Corydoras_habrosus",
    },
    {
        "id": "fish-090", "slug": "clown-loach",
        "commonName": "Clown Loach", "scientificName": "Chromobotia macracanthus",
        "family": "Botiidae", "origin": "Sumatra and Borneo",
        "adultSize": "20–30 cm", "minTankSize": "450 L",
        "waterColumn": "Bottom to mid",
        "temperament": "Peaceful (active and social)",
        "schooling": "Yes", "minGroupSize": 5,
        "diet": "Omnivore (loves snails)",
        "feedingNotes": "Sinking pellet, frozen bloodworm and shrimp, snails as natural pest control.",
        "tempRange": "25–30", "phRange": "6.0–7.5", "dghRange": "5–15",
        "flowRate": "Medium to high", "lifespan": "20–25",
        "difficulty": 3, "plantSafe": "Yes",
        "shrimpSafe": "No",
        "breedingDifficulty": "Very hard (almost never bred in home tanks)",
        "rarity": 2,
        "careSummary": "The orange and black classic that grows up to 30 cm in a proper tank. Routinely sold as a 4 cm juvenile to keepers with 60 L tanks. Long-lived (25+ years) and highly social, never keep singly. Hardcoded for nano-tanks: no.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Clown_loach",
    },
    {
        "id": "fish-091", "slug": "florida-flagfish",
        "commonName": "Florida Flagfish", "scientificName": "Jordanella floridae",
        "family": "Cyprinodontidae", "origin": "Florida and the southeastern United States",
        "adultSize": "5–6 cm", "minTankSize": "75 L",
        "waterColumn": "All",
        "temperament": "Semi-aggressive (fin-nipper if under-shoaled)",
        "schooling": "Loose group", "minGroupSize": 4,
        "diet": "Omnivore (heavy algae grazer)",
        "feedingNotes": "Flake, pellet, frozen food, and an unusual willingness to eat hair algae and black beard algae.",
        "tempRange": "18–26", "phRange": "6.5–8.0", "dghRange": "5–20",
        "flowRate": "Low to Medium", "lifespan": "3–5",
        "difficulty": 1, "plantSafe": "Yes",
        "shrimpSafe": "Adults only",
        "breedingDifficulty": "Easy",
        "rarity": 3,
        "careSummary": "Native to Florida wetlands and one of the few fish that genuinely eats hair algae and black beard algae in a freshwater tank. Males flush red, blue, and gold during breeding display. Tolerates cool water — pairs with white cloud minnows and weather loaches in unheated tanks.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Jordanella_floridae",
    },
    {
        "id": "fish-092", "slug": "pacific-blue-eye",
        "commonName": "Pacific Blue Eye", "scientificName": "Pseudomugil signifer",
        "family": "Pseudomugilidae", "origin": "Eastern Australia",
        "adultSize": "3–5 cm", "minTankSize": "60 L",
        "waterColumn": "Top to mid",
        "temperament": "Peaceful",
        "schooling": "Yes", "minGroupSize": 8,
        "diet": "Carnivore",
        "feedingNotes": "Micro pellet, daphnia, baby brine shrimp, crushed flake at the surface.",
        "tempRange": "18–28", "phRange": "6.5–8.0", "dghRange": "8–25",
        "flowRate": "Low to Medium", "lifespan": "2–3",
        "difficulty": 2, "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Medium",
        "rarity": 3,
        "careSummary": "Slim silver body with bright blue-glowing eyes and finnage edged in gold. Tolerates a wide range of hardness (some populations are brackish in the wild). Males fin-flick at each other in mock combat, all bluster, no harm.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pacific_blue_eye",
    },
]


TEMPLATE = """  {{
    id: "{id}",
    slug: "{slug}",
    category: "fish",
    commonName: "{commonName}",
    scientificName: "{scientificName}",
    family: "{family}",
    origin: "{origin}",
    adultSize: "{adultSize}",
    minTankSize: "{minTankSize}",
    waterColumn: "{waterColumn}",
    temperament: "{temperament}",
    schooling: "{schooling}",
    minGroupSize: {minGroupSize},
    diet: "{diet}",
    feedingNotes: "{feedingNotes}",
    tempRange: "{tempRange}",
    phRange: "{phRange}",
    dghRange: "{dghRange}",
    flowRate: "{flowRate}",
    lifespan: "{lifespan}",
    difficulty: {difficulty},
    plantSafe: "{plantSafe}",
    shrimpSafe: "{shrimpSafe}",
    breedingDifficulty: "{breedingDifficulty}",
    rarity: {rarity},
    careSummary: "{careSummary}",
    imageSourceUrl: "{imageSourceUrl}",
    imageLicenseHint: "Commons (mostly CC-BY-SA)",
  }},"""


def main() -> None:
    src = FISH_TS.read_text(encoding="utf-8")
    if "] as const;" not in src:
        raise SystemExit("Could not find closing `] as const;`")
    rendered = []
    for entry in NEW_FISH:
        safe = {k: (v.replace('"', '\\"') if isinstance(v, str) else v) for k, v in entry.items()}
        rendered.append(TEMPLATE.format(**safe))
    block = "\n".join(rendered) + "\n"
    FISH_TS.write_text(src.replace("] as const;", block + "] as const;"), encoding="utf-8")
    print(f"OK — appended {len(NEW_FISH)} fish")


if __name__ == "__main__":
    main()
