#!/usr/bin/env python3
"""Append 20 new fish entries to src/data/fish.ts before the closing `] as const;`."""

from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FISH_TS = ROOT / "src" / "data" / "fish.ts"

# Highest existing id is fish-057.
NEW_FISH = [
    {
        "id": "fish-058",
        "slug": "betta",
        "commonName": "Siamese Fighting Fish",
        "scientificName": "Betta splendens",
        "family": "Osphronemidae",
        "origin": "Mekong basin, Thailand and Cambodia",
        "adultSize": "6–7 cm",
        "minTankSize": "20 L",
        "waterColumn": "All",
        "temperament": "Territorial (single male per tank)",
        "schooling": "No",
        "minGroupSize": 1,
        "diet": "Carnivore",
        "feedingNotes": "Betta-specific pellets, frozen bloodworm, daphnia, brine shrimp. Skip flakes — most bettas spit them out.",
        "tempRange": "24–28",
        "phRange": "6.0–7.5",
        "dghRange": "3–15",
        "flowRate": "Very low",
        "lifespan": "3–5",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (adult bettas pick off shrimp)",
        "breedingDifficulty": "Medium",
        "rarity": 1,
        "careSummary": "Centrepiece nano fish with personality and presence — the male's fins and colour are an aquascape feature on their own. Single males only; two males will fight. Filtered, heated, planted tank is the standard, not the unfiltered bowl.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Betta_splendens",
    },
    {
        "id": "fish-059",
        "slug": "pristella-tetra",
        "commonName": "Pristella Tetra",
        "scientificName": "Pristella maxillaris",
        "family": "Characidae",
        "origin": "Amazon and Orinoco basins",
        "adultSize": "4–5 cm",
        "minTankSize": "75 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 8,
        "diet": "Omnivore",
        "feedingNotes": "Flake, micro pellets, frozen daphnia and bloodworm. Eats most things.",
        "tempRange": "22–28",
        "phRange": "6.0–7.5",
        "dghRange": "3–15",
        "flowRate": "Low to Medium",
        "lifespan": "4–5",
        "difficulty": 1,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "Also called the X-ray tetra for its translucent body and the yellow-black-white triangle on each fin. Tougher than the neon tetra and tolerates a much wider water-parameter range, the right call for hard-water tap setups.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pristella_maxillaris",
    },
    {
        "id": "fish-060",
        "slug": "bleeding-heart-tetra",
        "commonName": "Bleeding Heart Tetra",
        "scientificName": "Hyphessobrycon erythrostigma",
        "family": "Characidae",
        "origin": "Upper Amazon basin",
        "adultSize": "6–7 cm",
        "minTankSize": "110 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful (mild fin-nipper if under-shoaled)",
        "schooling": "Yes",
        "minGroupSize": 8,
        "diet": "Omnivore",
        "feedingNotes": "Flake, micro pellets, frozen daphnia, bloodworm, brine shrimp.",
        "tempRange": "23–28",
        "phRange": "5.5–7.0",
        "dghRange": "1–15",
        "flowRate": "Low to Medium",
        "lifespan": "5–7",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Very hard",
        "rarity": 2,
        "careSummary": "A larger, deeper-bodied tetra with a distinctive red blotch over the gills — the namesake bleeding heart. Needs space and a proper shoal; kept in fours they become twitchy fin-nippers, kept in eights they school calmly.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Hyphessobrycon_erythrostigma",
    },
    {
        "id": "fish-061",
        "slug": "penguin-tetra",
        "commonName": "Penguin Tetra",
        "scientificName": "Thayeria boehlkei",
        "family": "Characidae",
        "origin": "Amazon basin",
        "adultSize": "5–6 cm",
        "minTankSize": "90 L",
        "waterColumn": "Mid to top",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 8,
        "diet": "Omnivore",
        "feedingNotes": "Flake, micro pellets, frozen and live small foods.",
        "tempRange": "22–28",
        "phRange": "5.8–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "lifespan": "4–6",
        "difficulty": 1,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "Holds an unusual head-up tilt at rest, with a black band running from gill plate to the lower lobe of the tail. The angle is distinctive in a planted tank and reads well against green backgrounds. Tougher than most tetras.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Thayeria_boehlkei",
    },
    {
        "id": "fish-062",
        "slug": "serpae-tetra",
        "commonName": "Serpae Tetra",
        "scientificName": "Hyphessobrycon eques",
        "family": "Characidae",
        "origin": "Amazon and Paraguay basins",
        "adultSize": "4–5 cm",
        "minTankSize": "90 L",
        "waterColumn": "Mid",
        "temperament": "Semi-aggressive (fin-nipper)",
        "schooling": "Yes",
        "minGroupSize": 8,
        "diet": "Omnivore",
        "feedingNotes": "Flake, micro pellets, frozen daphnia and bloodworm.",
        "tempRange": "22–27",
        "phRange": "5.5–7.5",
        "dghRange": "2–15",
        "flowRate": "Low to Medium",
        "lifespan": "5–7",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (adults pick at shrimplets)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "Deep red body with a black comma marking behind the gill and bold black-and-white fins. Known fin-nipper, never house with bettas, angelfish, or long-finned gouramis. A tight shoal of 10+ keeps the aggression internal.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Hyphessobrycon_eques",
    },
    {
        "id": "fish-063",
        "slug": "denison-barb",
        "commonName": "Roseline Shark",
        "scientificName": "Sahyadria denisonii",
        "family": "Cyprinidae",
        "origin": "Western Ghats, India",
        "adultSize": "12–15 cm",
        "minTankSize": "250 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 6,
        "diet": "Omnivore",
        "feedingNotes": "Sinking pellet, flake, frozen bloodworm, blanched veg.",
        "tempRange": "18–25",
        "phRange": "6.5–7.8",
        "dghRange": "5–20",
        "flowRate": "Medium to high",
        "lifespan": "5–8",
        "difficulty": 3,
        "plantSafe": "Yes",
        "shrimpSafe": "No (size + activity)",
        "breedingDifficulty": "Very hard",
        "rarity": 3,
        "careSummary": "An active, river-system barb with a striking red-tipped tail and a black-and-gold lateral stripe. Endangered in the wild and protected by Indian export limits, captive-bred fish are the right purchase. Needs a long tank with flow.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Sahyadria_denisonii",
    },
    {
        "id": "fish-064",
        "slug": "gold-barb",
        "commonName": "Gold Barb",
        "scientificName": "Barbodes semifasciolatus",
        "family": "Cyprinidae",
        "origin": "Red River basin, China and Vietnam",
        "adultSize": "6–8 cm",
        "minTankSize": "75 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 6,
        "diet": "Omnivore",
        "feedingNotes": "Flake, sinking pellet, frozen daphnia, blanched veg.",
        "tempRange": "18–24",
        "phRange": "6.0–8.0",
        "dghRange": "5–20",
        "flowRate": "Low to Medium",
        "lifespan": "4–6",
        "difficulty": 1,
        "plantSafe": "Yes",
        "shrimpSafe": "Adults only (may nip shrimplets)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "A cooler-water barb in metallic gold with black flecks, often confused with the China barb. Tolerates a wider temperature range than most tropicals, the right fish for an unheated room-temperature tank.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Barbodes_semifasciolatus",
    },
    {
        "id": "fish-065",
        "slug": "rosy-barb",
        "commonName": "Rosy Barb",
        "scientificName": "Pethia conchonius",
        "family": "Cyprinidae",
        "origin": "Northern India, Bangladesh, Nepal",
        "adultSize": "8–10 cm",
        "minTankSize": "100 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful (mild fin-nipper if under-shoaled)",
        "schooling": "Yes",
        "minGroupSize": 6,
        "diet": "Omnivore",
        "feedingNotes": "Flake, pellet, blanched veg, frozen daphnia and bloodworm.",
        "tempRange": "18–24",
        "phRange": "6.0–8.0",
        "dghRange": "5–20",
        "flowRate": "Medium",
        "lifespan": "5–7",
        "difficulty": 1,
        "plantSafe": "Yes",
        "shrimpSafe": "Adults only",
        "breedingDifficulty": "Easy",
        "rarity": 2,
        "careSummary": "Males flush a deep raspberry pink during display, especially in cooler water. Active subtropical fish that does best at room temperature — pairs well with white cloud mountain minnows and weather loaches in unheated planted tanks.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pethia_conchonius",
    },
    {
        "id": "fish-066",
        "slug": "yoyo-loach",
        "commonName": "Yoyo Loach",
        "scientificName": "Botia almorhae",
        "family": "Botiidae",
        "origin": "Ganges and Indus basins",
        "adultSize": "10–15 cm",
        "minTankSize": "150 L",
        "waterColumn": "Bottom",
        "temperament": "Peaceful (interactive)",
        "schooling": "Yes",
        "minGroupSize": 5,
        "diet": "Omnivore (loves snails)",
        "feedingNotes": "Sinking pellet, frozen bloodworm and shrimp, snail control as a bonus.",
        "tempRange": "23–28",
        "phRange": "6.5–7.8",
        "dghRange": "5–15",
        "flowRate": "Medium",
        "lifespan": "10–15",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (eats shrimp readily)",
        "breedingDifficulty": "Very hard",
        "rarity": 2,
        "careSummary": "Named for the Y-O-Y-O pattern on the silver body. Highly social and visibly happier in groups of five or more, with regular play behaviour like chasing and rolling. The classic loach solution for a snail outbreak.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Botia_almorhae",
    },
    {
        "id": "fish-067",
        "slug": "clown-pleco",
        "commonName": "Clown Pleco",
        "scientificName": "Panaqolus maccus",
        "family": "Loricariidae",
        "origin": "Venezuela and Colombia",
        "adultSize": "9–10 cm",
        "minTankSize": "90 L",
        "waterColumn": "Bottom",
        "temperament": "Peaceful",
        "schooling": "No",
        "minGroupSize": 1,
        "diet": "Herbivore (wood-eater)",
        "feedingNotes": "Driftwood is mandatory, plus algae wafers, blanched courgette, sinking veg pellets.",
        "tempRange": "23–29",
        "phRange": "6.5–7.8",
        "dghRange": "5–15",
        "flowRate": "Medium",
        "lifespan": "10–12",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes",
        "breedingDifficulty": "Hard",
        "rarity": 2,
        "careSummary": "A small striped pleco that stays under 10 cm and actively rasps driftwood, which it needs for digestion. Almost always hides during the day, comes out at dusk. The right pleco for tanks too small for a common pleco.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Panaqolus_maccus",
    },
    {
        "id": "fish-068",
        "slug": "glass-catfish",
        "commonName": "Glass Catfish",
        "scientificName": "Kryptopterus vitreolus",
        "family": "Siluridae",
        "origin": "Thailand, southern Mekong basin",
        "adultSize": "6–8 cm",
        "minTankSize": "100 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful (timid)",
        "schooling": "Yes",
        "minGroupSize": 6,
        "diet": "Carnivore",
        "feedingNotes": "Frozen and live small foods — daphnia, baby brine shrimp, micro worms. Most refuse dry food.",
        "tempRange": "22–26",
        "phRange": "6.0–7.5",
        "dghRange": "2–15",
        "flowRate": "Medium",
        "lifespan": "5–8",
        "difficulty": 3,
        "plantSafe": "Yes",
        "shrimpSafe": "Adults only (may eat shrimplets)",
        "breedingDifficulty": "Very hard",
        "rarity": 3,
        "careSummary": "Completely transparent — only the silver swim bladder and the skeleton are visible. Shoals mid-water and refuses to come down to the substrate. Sensitive to water-quality swings and shy, never keep singly or in pairs.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Kryptopterus_vitreolus",
    },
    {
        "id": "fish-069",
        "slug": "pictus-catfish",
        "commonName": "Pictus Catfish",
        "scientificName": "Pimelodus pictus",
        "family": "Pimelodidae",
        "origin": "Orinoco and Amazon basins",
        "adultSize": "13–15 cm",
        "minTankSize": "200 L",
        "waterColumn": "Bottom to mid",
        "temperament": "Peaceful (active)",
        "schooling": "Yes",
        "minGroupSize": 3,
        "diet": "Omnivore (carnivore-leaning)",
        "feedingNotes": "Sinking pellet, frozen bloodworm and shrimp, small live food.",
        "tempRange": "23–28",
        "phRange": "6.5–7.8",
        "dghRange": "5–15",
        "flowRate": "Medium to high",
        "lifespan": "8–10",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (will eat shrimp)",
        "breedingDifficulty": "Very hard",
        "rarity": 3,
        "careSummary": "Silver body with sharp black dots, plus long barbels and pectoral spines that can catch in nets — net carefully with a coarse mesh or use a cup. Highly active and will eat any fish small enough to fit in its mouth, plan tank mates above 5 cm.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pimelodus_pictus",
    },
    {
        "id": "fish-070",
        "slug": "chocolate-gourami",
        "commonName": "Chocolate Gourami",
        "scientificName": "Sphaerichthys osphromenoides",
        "family": "Osphronemidae",
        "origin": "Borneo, Sumatra, peninsular Malaysia",
        "adultSize": "5–6 cm",
        "minTankSize": "75 L",
        "waterColumn": "Mid to top",
        "temperament": "Peaceful (delicate)",
        "schooling": "Yes",
        "minGroupSize": 4,
        "diet": "Carnivore",
        "feedingNotes": "Live and frozen small foods — daphnia, baby brine shrimp, micro worms. Most refuse dry food.",
        "tempRange": "26–30",
        "phRange": "4.0–6.5",
        "dghRange": "0–5",
        "flowRate": "Very low",
        "lifespan": "3–5",
        "difficulty": 4,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Hard",
        "rarity": 3,
        "careSummary": "An expert-only gourami that demands blackwater — soft, acidic, tannin-stained, warm and still. Mouthbrooder. Pairs poorly with most community fish; best in a single-species blackwater biotope with botanicals and floating plants.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Chocolate_gourami",
    },
    {
        "id": "fish-071",
        "slug": "licorice-gourami",
        "commonName": "Licorice Gourami",
        "scientificName": "Parosphromenus deissneri",
        "family": "Osphronemidae",
        "origin": "Bangka Island, Indonesia (peat swamps)",
        "adultSize": "3–4 cm",
        "minTankSize": "30 L",
        "waterColumn": "Mid to top",
        "temperament": "Peaceful (highly delicate)",
        "schooling": "No (pairs)",
        "minGroupSize": 2,
        "diet": "Carnivore",
        "feedingNotes": "Live food only in most cases — micro worms, baby brine shrimp, vinegar eels.",
        "tempRange": "22–28",
        "phRange": "3.5–5.5",
        "dghRange": "0–3",
        "flowRate": "Very low",
        "lifespan": "3–4",
        "difficulty": 5,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes",
        "breedingDifficulty": "Hard",
        "rarity": 4,
        "careSummary": "A peat-swamp specialist that needs pH 4 to 5 water and live food to thrive. Stunning when displaying — males flare into red, blue, and gold barring. Single-species blackwater tank only, do not mix with community fish or even shrimp.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Parosphromenus_deissneri",
    },
    {
        "id": "fish-072",
        "slug": "croaking-gourami",
        "commonName": "Croaking Gourami",
        "scientificName": "Trichopsis vittata",
        "family": "Osphronemidae",
        "origin": "Mekong basin and peninsular Thailand",
        "adultSize": "5–7 cm",
        "minTankSize": "60 L",
        "waterColumn": "Mid to top",
        "temperament": "Peaceful",
        "schooling": "No",
        "minGroupSize": 1,
        "diet": "Carnivore",
        "feedingNotes": "Small pellet, frozen daphnia, bloodworm, brine shrimp.",
        "tempRange": "22–28",
        "phRange": "6.0–7.5",
        "dghRange": "2–15",
        "flowRate": "Very low",
        "lifespan": "3–5",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes (with adults)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "Named for the audible croaking sound males make when displaying. Hardier than sparkling gourami and tolerates a broader range of parameters. The right nano gourami for a peaceful community of small tetras and rasboras.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Trichopsis_vittata",
    },
    {
        "id": "fish-073",
        "slug": "phoenix-rasbora",
        "commonName": "Phoenix Rasbora",
        "scientificName": "Boraras merah",
        "family": "Cyprinidae",
        "origin": "Borneo, peat swamps",
        "adultSize": "1.5–2 cm",
        "minTankSize": "30 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 10,
        "diet": "Omnivore",
        "feedingNotes": "Crushed micro pellet, baby brine shrimp, micro worms, finely crushed flake.",
        "tempRange": "23–28",
        "phRange": "4.5–6.5",
        "dghRange": "0–6",
        "flowRate": "Very low",
        "lifespan": "3–4",
        "difficulty": 3,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes",
        "breedingDifficulty": "Hard",
        "rarity": 3,
        "careSummary": "A tiny blackwater Boraras with bright red-orange flanks broken by sharp black blotches — like a phoenix marking. Tighter shoals than chili rasboras when comfortable. Nano blackwater biotopes only, never mix with anything over 4 cm.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Boraras_merah",
    },
    {
        "id": "fish-074",
        "slug": "dwarf-rasbora",
        "commonName": "Dwarf Rasbora",
        "scientificName": "Boraras maculatus",
        "family": "Cyprinidae",
        "origin": "Malaysia, Sumatra, Borneo",
        "adultSize": "1.5–2 cm",
        "minTankSize": "30 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 10,
        "diet": "Omnivore",
        "feedingNotes": "Crushed flake, micro pellet, baby brine shrimp, micro worms.",
        "tempRange": "23–28",
        "phRange": "5.0–7.0",
        "dghRange": "1–8",
        "flowRate": "Very low",
        "lifespan": "3–4",
        "difficulty": 3,
        "plantSafe": "Yes",
        "shrimpSafe": "Yes",
        "breedingDifficulty": "Hard",
        "rarity": 3,
        "careSummary": "Distinguished from other Boraras by the three sharp black spots — one at the gill, one mid-body, one at the tail base. Slightly more tolerant of harder water than chili or phoenix rasboras. Reads brilliantly against tannin-stained water.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Boraras_maculatus",
    },
    {
        "id": "fish-075",
        "slug": "indian-glassfish",
        "commonName": "Indian Glass Fish",
        "scientificName": "Parambassis ranga",
        "family": "Ambassidae",
        "origin": "India, Bangladesh, Myanmar",
        "adultSize": "6–7 cm",
        "minTankSize": "75 L",
        "waterColumn": "Mid",
        "temperament": "Peaceful",
        "schooling": "Yes",
        "minGroupSize": 6,
        "diet": "Carnivore",
        "feedingNotes": "Live and frozen small foods preferred — daphnia, baby brine shrimp, mosquito larvae.",
        "tempRange": "20–28",
        "phRange": "7.0–8.5",
        "dghRange": "8–20",
        "flowRate": "Low to Medium",
        "lifespan": "3–5",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (eats shrimp)",
        "breedingDifficulty": "Medium",
        "rarity": 2,
        "careSummary": "Genuinely transparent like the glass catfish, with the skeleton clearly visible. Strictly freshwater despite some shops keeping them brackish. Never buy dyed (\"painted glass\") specimens — the injection process kills most fish.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Parambassis_ranga",
    },
    {
        "id": "fish-076",
        "slug": "golden-wonder-killifish",
        "commonName": "Golden Wonder Killifish",
        "scientificName": "Aplocheilus lineatus",
        "family": "Aplocheilidae",
        "origin": "Southern India and Sri Lanka",
        "adultSize": "8–10 cm",
        "minTankSize": "75 L",
        "waterColumn": "Top",
        "temperament": "Semi-aggressive (predatory)",
        "schooling": "No (loose group)",
        "minGroupSize": 1,
        "diet": "Carnivore",
        "feedingNotes": "Floating pellet, frozen bloodworm, live insects, small live fish are eaten without hesitation.",
        "tempRange": "22–28",
        "phRange": "6.0–7.5",
        "dghRange": "5–20",
        "flowRate": "Low",
        "lifespan": "3–5",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (eats shrimp)",
        "breedingDifficulty": "Medium",
        "rarity": 3,
        "careSummary": "A surface predator with metallic gold flanks and bright red fins. The hardier of the popular killifish, not annual like Nothobranchius. Will eat any fish small enough to fit — keep with mid-sized tank mates above 4 cm, never with neons or shrimplets.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Aplocheilus_lineatus",
    },
    {
        "id": "fish-077",
        "slug": "dojo-loach",
        "commonName": "Dojo Loach",
        "scientificName": "Misgurnus anguillicaudatus",
        "family": "Cobitidae",
        "origin": "East Asia (Japan, China, Korea, Vietnam)",
        "adultSize": "15–20 cm",
        "minTankSize": "200 L",
        "waterColumn": "Bottom",
        "temperament": "Peaceful (interactive)",
        "schooling": "Yes",
        "minGroupSize": 3,
        "diet": "Omnivore",
        "feedingNotes": "Sinking pellet, frozen bloodworm and shrimp, blanched veg, scavenges leftovers.",
        "tempRange": "10–24",
        "phRange": "6.5–8.0",
        "dghRange": "5–20",
        "flowRate": "Medium",
        "lifespan": "8–10",
        "difficulty": 2,
        "plantSafe": "Yes",
        "shrimpSafe": "No (eats shrimp)",
        "breedingDifficulty": "Hard",
        "rarity": 2,
        "careSummary": "Also called the weather loach — barometric pressure changes set them swimming wildly. Cold-tolerant, suits unheated room-temperature tanks alongside goldfish or white cloud minnows. Eel-like and burrows into substrate, sand is kinder than gravel.",
        "imageSourceUrl": "https://en.wikipedia.org/wiki/Pond_loach",
    },
]


TEMPLATE = """  {{
    id: "{id}",
    slug: "{slug}",
    category: "fish",
    commonName: "{commonName}",
    scientificName: "{scientificName}",
    family: "{family}",
    origin: "{origin}",
    adultSize: "{adultSize}",
    minTankSize: "{minTankSize}",
    waterColumn: "{waterColumn}",
    temperament: "{temperament}",
    schooling: "{schooling}",
    minGroupSize: {minGroupSize},
    diet: "{diet}",
    feedingNotes: "{feedingNotes}",
    tempRange: "{tempRange}",
    phRange: "{phRange}",
    dghRange: "{dghRange}",
    flowRate: "{flowRate}",
    lifespan: "{lifespan}",
    difficulty: {difficulty},
    plantSafe: "{plantSafe}",
    shrimpSafe: "{shrimpSafe}",
    breedingDifficulty: "{breedingDifficulty}",
    rarity: {rarity},
    careSummary: "{careSummary}",
    imageSourceUrl: "{imageSourceUrl}",
    imageLicenseHint: "Commons (mostly CC-BY-SA)",
  }},"""


def main() -> None:
    src = FISH_TS.read_text(encoding="utf-8")
    if "] as const;" not in src:
        raise SystemExit("Could not find closing `] as const;` in fish.ts")

    # Escape any double-quotes that already exist in field values for safe string interpolation.
    rendered = []
    for entry in NEW_FISH:
        safe = {k: (v.replace('"', '\\"') if isinstance(v, str) else v) for k, v in entry.items()}
        rendered.append(TEMPLATE.format(**safe))
    block = "\n".join(rendered) + "\n"

    new_src = src.replace("] as const;", block + "] as const;")
    FISH_TS.write_text(new_src, encoding="utf-8")
    print(f"OK — appended {len(NEW_FISH)} fish to {FISH_TS}")


if __name__ == "__main__":
    main()
