"""
Fix the 4 shrimp images that were incorrectly using shared photos from
the original scrape pass:

  - bee-shrimp            ← previously Crystal Red (wrong genus morph)
  - blue-bolt-shrimp      ← previously Crystal Red (wrong colour line)
  - blue-dream-shrimp     ← previously Red Cherry (wrong colour)
  - yellow-shrimp         ← previously Red Cherry (wrong colour)

Each entry below names the correct Wikimedia Commons file. The script
downloads a ~1200 px copy into public/images/catalogue/shrimp/<slug>.jpg
(overwriting the wrong one) and rewrites the matching entry in
src/data/image-attribution.ts with the correct fileTitle, author,
license, and descriptionUrl. All four sources are commercial-use safe
(CC BY 4.0 or CC BY-SA 4.0/3.0) and credited per the license terms.

Run from project root:
  python3 scripts/fix-shrimp-images.py
"""
from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path
from typing import Optional

import requests

COMMONS_API = "https://commons.wikimedia.org/w/api.php"
USER_AGENT = (
    "FinAndStem/0.1 (https://finandstem.com; finandstem@gmail.com) requests"
)
HEADERS = {"User-Agent": USER_AGENT}

ROOT = Path(__file__).resolve().parent.parent
PUBLIC_IMG = ROOT / "public" / "images" / "catalogue" / "shrimp"
ATTRIB_TS = ROOT / "src" / "data" / "image-attribution.ts"
TARGET_WIDTH = 1200

TAG_RE = re.compile(r"<[^>]+>")
WHITESPACE_RE = re.compile(r"\s+")


# (slug, common name, scientific name, exact Commons File: title, Wikipedia URL)
TARGETS = [
    (
        "bee-shrimp",
        "Bee Shrimp (wild)",
        "Caridina cantonensis",
        "File:Caridina-cf-cantonensis-black-bee.jpg",
        "https://en.wikipedia.org/wiki/Caridina_cantonensis",
    ),
    (
        "blue-bolt-shrimp",
        "Blue Bolt Shrimp",
        "Caridina cantonensis 'Blue Bolt'",
        "File:Caridina-cf-cantonensis-blue-bolt.jpg",
        "https://en.wikipedia.org/wiki/Caridina_cantonensis",
    ),
    (
        "blue-dream-shrimp",
        "Blue Dream Shrimp",
        "Neocaridina davidi 'Blue Dream'",
        "File:Blue dream Neocaridina davidi.jpg",
        "https://en.wikipedia.org/wiki/Neocaridina_davidi",
    ),
    (
        "yellow-shrimp",
        "Yellow Shrimp",
        "Neocaridina davidi 'Yellow'",
        "File:Neocaridina-heteropoda-var-yellow.jpg",
        "https://en.wikipedia.org/wiki/Neocaridina_davidi",
    ),
]


def clean(s: Optional[str]) -> str:
    if not s:
        return ""
    s = html.unescape(s)
    return WHITESPACE_RE.sub(" ", TAG_RE.sub(" ", s)).strip()


def fetch_metadata(file_title: str) -> Optional[dict]:
    params = {
        "action": "query",
        "format": "json",
        "prop": "imageinfo",
        "iiprop": "url|extmetadata|mime|size",
        "iiurlwidth": TARGET_WIDTH,
        "titles": file_title,
    }
    r = requests.get(COMMONS_API, params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    pages = (r.json().get("query") or {}).get("pages") or {}
    for _pid, page in pages.items():
        infos = page.get("imageinfo")
        if not infos:
            return None
        info = infos[0]
        meta = info.get("extmetadata", {})

        def gv(key: str) -> Optional[str]:
            v = meta.get(key)
            return v.get("value") if v else None

        return {
            "fileTitle": file_title,
            "url": info.get("thumburl") or info.get("url"),
            "mime": info.get("mime"),
            "width": info.get("thumbwidth") or info.get("width"),
            "height": info.get("thumbheight") or info.get("height"),
            "license": clean(gv("LicenseShortName")),
            "licenseUrl": gv("LicenseUrl"),
            "author": clean(gv("Artist")) or "Unknown",
            "credit": clean(gv("Credit")),
            "descriptionUrl": info.get("descriptionurl"),
        }
    return None


def download(url: str, dest: Path) -> None:
    r = requests.get(url, headers=HEADERS, stream=True, timeout=120)
    r.raise_for_status()
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "wb") as f:
        for chunk in r.iter_content(8192):
            f.write(chunk)


def load_attribution() -> dict:
    raw = ATTRIB_TS.read_text()
    m = re.search(
        r"IMAGE_ATTRIBUTION:[^=]+=\s*(\{[\s\S]*\})\s*as const;",
        raw,
    )
    if not m:
        sys.exit("Could not parse attribution file")
    return json.loads(m.group(1))


def write_attribution(d: dict) -> None:
    body = json.dumps(d, indent=2, ensure_ascii=False, sort_keys=True)
    ATTRIB_TS.write_text(
        "// Auto-generated by scripts/scrape-images.py — do not edit by hand.\n"
        "// Run that script to refresh after image edits or new entries.\n\n"
        'import type { ImageAttribution } from "@/types/catalogue";\n\n'
        f"export const IMAGE_ATTRIBUTION: Record<string, ImageAttribution> = {body} as const;\n"
    )


def main() -> int:
    attribution = load_attribution()
    PUBLIC_IMG.mkdir(parents=True, exist_ok=True)

    for slug, common, scientific, file_title, wiki_url in TARGETS:
        print(f"[fix] {slug}  ← {file_title}")
        meta = fetch_metadata(file_title)
        if not meta or not meta.get("url"):
            print("       ! could not fetch metadata, skipping")
            continue

        dest = PUBLIC_IMG / f"{slug}.jpg"
        # Overwrite the wrong file
        if dest.exists():
            dest.unlink()
        download(meta["url"], dest)

        attribution[slug] = {
            "slug": slug,
            "category": "shrimp",
            "src": f"/images/catalogue/shrimp/{slug}.jpg",
            "alt": f"{common} ({scientific})",
            "width": meta.get("width"),
            "height": meta.get("height"),
            "license": meta.get("license"),
            "licenseUrl": meta.get("licenseUrl"),
            "author": meta.get("author"),
            "credit": meta.get("credit"),
            "fileTitle": meta.get("fileTitle"),
            "descriptionUrl": meta.get("descriptionUrl"),
            "wikipediaUrl": wiki_url,
        }
        print(
            f"       ok  {meta.get('license')}  "
            f"{meta.get('width')}x{meta.get('height')}  by {meta.get('author')}"
        )

    cleaned = {
        slug: {k: v for k, v in rec.items() if v is not None}
        for slug, rec in attribution.items()
    }
    write_attribution(cleaned)
    print(f"\nUpdated attribution for {len(TARGETS)} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
