"""
Final-fallback scraper using Commons full-text search.
Targets the 4 entries still without images.
"""
from __future__ import annotations

import html
import json
import re
import sys
import time
from pathlib import Path
from typing import Optional

import requests

COMMONS_API = "https://commons.wikimedia.org/w/api.php"
USER_AGENT = (
    "FinAndStem/0.1 (https://finandstem.example.com; mikee@dsg.co.za) requests"
)
HEADERS = {"User-Agent": USER_AGENT}

ROOT = Path(__file__).resolve().parent.parent
PUBLIC_IMG = ROOT / "public" / "images" / "catalogue"
ATTRIB_TS = ROOT / "src" / "data" / "image-attribution.ts"
TARGET_WIDTH = 1200

TAG_RE = re.compile(r"<[^>]+>")
WHITESPACE_RE = re.compile(r"\s+")

SKIP_HINTS = (
    "icon", "logo", "map", "stub", "wiki", "distribution", "range",
    "disambig", "dab list", "merge-arrow", "infosign", "question",
    "padlock", "loudspeaker",
)
SKIP_MIMES = ("image/svg+xml",)
ACCEPT_MIMES = ("image/jpeg", "image/png", "image/webp", "image/jpg")


# (slug, category, commonName, scientificName, [search queries to try in order])
TARGETS = [
    ("monte-carlo", "plants", "Monte Carlo",
     "Micranthemum tweediei", ["Micranthemum tweediei aquarium", "Micranthemum tweediei planted tank", "Hemianthus callitrichoides"]),
    ("java-moss", "mosses", "Java Moss",
     "Taxiphyllum barbieri", ["Taxiphyllum barbieri", "Java moss aquarium"]),
    ("weeping-moss", "mosses", "Weeping Moss",
     "Vesicularia ferriei", ["Vesicularia dubyana", "weeping moss planted tank", "aquarium moss driftwood"]),
    ("mini-christmas-moss", "mosses", "Mini Christmas Moss",
     "Vesicularia sp.", ["Vesicularia montagnei", "Christmas moss bonsai"]),
]


def clean(s: Optional[str]) -> str:
    if not s:
        return ""
    s = html.unescape(s)
    return WHITESPACE_RE.sub(" ", TAG_RE.sub(" ", s)).strip()


def search_commons(query: str, limit: int = 25) -> list[str]:
    """Return File:* titles ranked by Commons search relevance."""
    params = {
        "action": "query",
        "format": "json",
        "generator": "search",
        "gsrnamespace": 6,
        "gsrsearch": query,
        "gsrlimit": limit,
        "prop": "imageinfo",
        "iiprop": "url|extmetadata|mime|size",
        "iiurlwidth": TARGET_WIDTH,
    }
    r = requests.get(COMMONS_API, params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    pages = r.json().get("query", {}).get("pages", {})
    # Sort by 'index' to preserve search rank
    sorted_pages = sorted(
        pages.values(), key=lambda p: p.get("index", 9999)
    )
    return sorted_pages


def looks_decorative(name: str) -> bool:
    n = name.lower()
    return any(h in n for h in SKIP_HINTS)


def is_commercial_safe(license_str: str) -> bool:
    if not license_str:
        return False
    s = license_str.lower()
    return not ("non-commercial" in s or "-nc" in s or "noncommercial" in s)


def ext_from_mime(mime: Optional[str]) -> str:
    if not mime:
        return "jpg"
    m = mime.lower()
    if "jpeg" in m or "jpg" in m:
        return "jpg"
    if "png" in m:
        return "png"
    if "webp" in m:
        return "webp"
    return "jpg"


def download(url: str, dest: Path) -> None:
    if dest.exists():
        return
    r = requests.get(url, headers=HEADERS, stream=True, timeout=120)
    r.raise_for_status()
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "wb") as f:
        for c in r.iter_content(8192):
            f.write(c)


def load_attribution() -> dict[str, dict]:
    raw = ATTRIB_TS.read_text()
    m = re.search(r"export const IMAGE_ATTRIBUTION[^=]*=\s*(\{[\s\S]*?\}) as const;", raw)
    return json.loads(m.group(1)) if m else {}


def write_attribution(d: dict[str, dict]) -> None:
    body = json.dumps(d, indent=2, ensure_ascii=False, sort_keys=True)
    ATTRIB_TS.write_text(
        "// Auto-generated by scripts/scrape-images.py — do not edit by hand.\n"
        "// Run that script to refresh after image edits or new entries.\n\n"
        'import type { ImageAttribution } from "@/types/catalogue";\n\n'
        f"export const IMAGE_ATTRIBUTION: Record<string, ImageAttribution> = {body} as const;\n"
    )


def pick(pages: list[dict]) -> Optional[dict]:
    for page in pages:
        title = page.get("title", "")
        if looks_decorative(title):
            continue
        infos = page.get("imageinfo")
        if not infos:
            continue
        info = infos[0]
        meta = info.get("extmetadata", {})

        def gv(k: str) -> Optional[str]:
            v = meta.get(k)
            return v.get("value") if v else None

        mime = info.get("mime")
        if mime not in ACCEPT_MIMES:
            continue
        license_ = clean(gv("LicenseShortName"))
        if not is_commercial_safe(license_):
            continue
        w = info.get("thumbwidth") or info.get("width") or 0
        if w < 400:
            continue
        return {
            "fileTitle": title,
            "url": info.get("thumburl") or info.get("url"),
            "mime": mime,
            "width": w,
            "height": info.get("thumbheight") or info.get("height"),
            "license": license_,
            "licenseUrl": gv("LicenseUrl"),
            "author": clean(gv("Artist")) or "Unknown",
            "credit": clean(gv("Credit")),
            "descriptionUrl": info.get("descriptionurl"),
        }
    return None


def main() -> int:
    attribution = load_attribution()
    for slug, category, common, scientific, queries in TARGETS:
        if slug in attribution:
            print(f"[skip] {slug} (already has image)")
            continue
        meta = None
        for q in queries:
            print(f"\n[search] {slug} :: {q!r}")
            try:
                pages = search_commons(q)
            except Exception as ex:
                print(f"  ! {ex}")
                continue
            print(f"  results: {len(pages)}")
            meta = pick(pages)
            if meta:
                break

        if not meta:
            print(f"  ! {slug} still no usable image")
            continue

        ext = ext_from_mime(meta.get("mime"))
        dest = PUBLIC_IMG / category / f"{slug}.{ext}"
        download(meta["url"], dest)
        attribution[slug] = {
            "slug": slug,
            "category": category,
            "src": f"/images/catalogue/{category}/{slug}.{ext}",
            "alt": f"{common} ({scientific})",
            "width": meta.get("width"),
            "height": meta.get("height"),
            "license": meta.get("license"),
            "licenseUrl": meta.get("licenseUrl"),
            "author": meta.get("author"),
            "credit": meta.get("credit"),
            "fileTitle": meta.get("fileTitle"),
            "descriptionUrl": meta.get("descriptionUrl"),
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{scientific.replace(' ', '_')}",
        }
        write_attribution(attribution)
        print(f"  ok  {meta.get('license')}  {meta.get('width')}x{meta.get('height')}  ← {meta.get('fileTitle')}")
        time.sleep(0.4)

    print(f"\nFinal: {len(attribution)} entries with images.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
