// Auto-generated by scripts/build-substrates.py for entries 1 to 17.
// Source of truth for entries 1-17: prompts/05-substrate-profiles-and-compare.md (Part 1).
// Entries 18 to 27 (extended aquasoil coverage) were added manually on 2026-05-28
// and live inline below the generated block.

import type { SubstrateEntry } from "@/types/substrate";

export const substrates: ReadonlyArray<SubstrateEntry> = [
  {
    "id": "substrate-001",
    "slug": "ada-amazonia-v2",
    "name": "ADA Aqua Soil Amazonia Ver.2",
    "brand": "Aqua Design Amano (ADA)",
    "category": "active-aquasoil",
    "countryOfOrigin": "Japan",
    "colour": "Dark brown to black",
    "grainSize": "2 to 5 mm",
    "phTarget": "5.8 to 6.5",
    "phEffect": "lowers-strong",
    "khEffect": "lowers-strong",
    "ammoniaRelease": "strong",
    "nutrientContent": "Very high",
    "bufferingLongevity": "18 to 24 months (RO), 12 to 18 months (treated tap)",
    "recommendedWater": "RO + remineraliser preferred, soft tap tolerable",
    "typicalPriceUsd": "$35 to $50 per 9L bag",
    "difficulty": 3,
    "bestFor": [
      "Caridina shrimp",
      "high-tech planted",
      "ADA-style Nature Aquarium"
    ],
    "shrimpSafe": true,
    "careSummary": "Aqua Soil Amazonia Ver.2 uses rare Japanese black soil with added \"Amazonia Supplement\" granules that enhance the nitrogen and humic content. The gold standard for Caridina shrimp tanks (Crystal Red, Bee, Blue Bolt morphs) because the active buffering holds pH in the 5.8 to 6.5 range that the genus requires.",
    "sections": {
      "howItWorks": "Aqua Soil Amazonia Ver.2 uses rare Japanese black soil with added \"Amazonia Supplement\" granules that enhance the nitrogen and humic content. The clay pellets are baked at low temperature so they retain shape underwater for years while gradually releasing nutrients to plant roots. After two weeks in a new tank, water tests show pH 5.8 and detectable ammonia around 5 mg/L. After six weeks, ammonia is no longer detectable and pH stabilises at 6.2.",
      "bestUseCases": "The gold standard for Caridina shrimp tanks (Crystal Red, Bee, Blue Bolt morphs) because the active buffering holds pH in the 5.8 to 6.5 range that the genus requires. Also the canonical choice for high-tech planted tanks running CO2 injection and EI dosing where strong root nutrition is the goal.",
      "commonMistakes": "Adding fish or shrimp before the ammonia cycle completes is the most common failure mode. Topping off with hard tap water exhausts the buffering capacity prematurely and shifts pH back toward neutral within months. Disturbing the substrate releases trapped ammonia into the water column and can cause a mini cycle.",
      "proTips": "A 3 cm layer at the front sloping to 6 cm at the back gives the planted-tank standard depth profile. Cap with a thin layer of inert sand only if a finer aesthetic is preferred; the cap can reduce nutrient flow to roots. The substrate is fragile, so avoid moving plants once established."
    },
    "sources": [
      {
        "label": "ADA: Make and Keep Aqua Soil Amazonia Ver.2",
        "url": "https://www.adana.co.jp/en/aquajournal/makeandkeep_20/"
      },
      {
        "label": "Aquasabi: ADA Aqua Soil Amazonia Ver.2 product page",
        "url": "https://www.aquasabi.com/ADA-Aqua-Soil-Amazonia-Ver2"
      },
      {
        "label": "Spec-Tanks: ADA Amazonia II Substrate Review",
        "url": "https://spec-tanks.com/ada-amazonia-ii-substrate-review/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-002",
    "slug": "ada-amazonia-powder-v2",
    "name": "ADA Aqua Soil Amazonia Powder Ver.2",
    "brand": "ADA",
    "category": "active-aquasoil",
    "countryOfOrigin": "Japan",
    "colour": "Dark brown to black",
    "grainSize": "1 to 2 mm",
    "phTarget": "5.8 to 6.5",
    "phEffect": "lowers-strong",
    "khEffect": "lowers-strong",
    "ammoniaRelease": "strong",
    "nutrientContent": "Very high",
    "bufferingLongevity": "18 to 24 months (RO), 12 to 18 months (treated tap)",
    "recommendedWater": "RO + remineraliser",
    "typicalPriceUsd": "$40 to $55 per 9L bag",
    "difficulty": 3,
    "bestFor": [
      "Carpeting plants (Monte Carlo",
      "dwarf hairgrass",
      "HC Cuba)",
      "top dressing"
    ],
    "shrimpSafe": true,
    "careSummary": "Identical chemistry to the standard Amazonia Ver.2 but with finer grain size (around 1 to 2 mm) that suits small-rooted carpet plants and produces a smoother visual surface. A 1 cm cap of powder type over 4 cm of standard Amazonia gives carpet plants a denser planting medium while the larger grains beneath maintain water flow through the substrate.",
    "sections": {
      "howItWorks": "Identical chemistry to the standard Amazonia Ver.2 but with finer grain size (around 1 to 2 mm) that suits small-rooted carpet plants and produces a smoother visual surface. Most aquarists layer the powder type over a standard-grain base.",
      "bestUseCases": "A 1 cm cap of powder type over 4 cm of standard Amazonia gives carpet plants a denser planting medium while the larger grains beneath maintain water flow through the substrate. Pure powder layouts work for low-flow nano tanks but compact over time.",
      "commonMistakes": "Pure powder substrate in deeper layers (more than 3 cm) compacts and develops anaerobic pockets. Mixing powder and standard grain rather than layering reduces the value of using powder at all.",
      "proTips": "Pour powder type onto a damp standard-grain base via a paper funnel so it forms a level top layer without disturbing the underlying soil. The carpet plant gripping behaviour is noticeably better than on standard grain."
    },
    "sources": [
      {
        "label": "Aquasabi: ADA Aqua Soil Amazonia Powder Type Ver.2",
        "url": "https://www.aquasabi.com/ADA-Aqua-Soil-Amazonia-Powder-Ver2"
      },
      {
        "label": "ADA: Aqua Soil product line",
        "url": "https://www.adana.co.jp/en/contents/aquasoil/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-003",
    "slug": "ada-africana",
    "name": "ADA Aqua Soil Africana",
    "brand": "ADA",
    "category": "active-aquasoil",
    "countryOfOrigin": "Japan",
    "colour": "Reddish brown",
    "grainSize": "2 to 5 mm",
    "phTarget": "5.8 to 6.5",
    "phEffect": "lowers-strong",
    "khEffect": "lowers-strong",
    "ammoniaRelease": "moderate",
    "nutrientContent": "Medium-high",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Soft tap or RO",
    "typicalPriceUsd": "$35 to $50 per 9L bag",
    "difficulty": 3,
    "bestFor": [
      "African biotope tanks",
      "alternative aesthetic to dark substrates"
    ],
    "shrimpSafe": true,
    "careSummary": "Africana uses a different clay source (laterite-rich African soil) that produces a distinctive reddish-brown grain. African biotope tanks (Lake Tanganyika, Lake Malawi if hardness can be raised separately, West African streams) where the reddish substrate matches the natural environment.",
    "sections": {
      "howItWorks": "Africana uses a different clay source (laterite-rich African soil) that produces a distinctive reddish-brown grain. Chemistry is similar to Amazonia but with slightly lower ammonia release and slightly lower nutrient density. The pH buffering effect is comparable.",
      "bestUseCases": "African biotope tanks (Lake Tanganyika, Lake Malawi if hardness can be raised separately, West African streams) where the reddish substrate matches the natural environment. The colour also pops the green of Anubias and other West African aquatic plants.",
      "commonMistakes": "Treating Africana as interchangeable with Amazonia. While the buffering profile is similar, Africana releases less ammonia, which means slower initial plant growth in the first two weeks. Heavy root feeders may need supplementation earlier than with Amazonia.",
      "proTips": "Pair with red volcanic stone (Maten stone, Frodo stone) for a coordinated warm-tone hardscape. Works particularly well with red colour-line stem plants because the reddish substrate amplifies their colour by reflection."
    },
    "sources": [
      {
        "label": "Aquasabi: ADA Aqua Soil Africana",
        "url": "https://www.aquasabi.com/ADA-Aqua-Soil-Africana"
      },
      {
        "label": "ADA: Aqua Soil product line",
        "url": "https://www.adana.co.jp/en/contents/aquasoil/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-004",
    "slug": "tropica-aquarium-soil",
    "name": "Tropica Aquarium Soil",
    "brand": "Tropica (Denmark)",
    "category": "active-aquasoil",
    "countryOfOrigin": "Denmark",
    "colour": "Dark brown",
    "grainSize": "2 to 3 mm",
    "phTarget": "6.0 to 7.0",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Medium",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap (broad tolerance) or RO",
    "typicalPriceUsd": "$25 to $35 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "Beginner planted tanks",
      "low-tech",
      "mixed community tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Tropica Aquarium Soil is the European mass-market answer to ADA Amazonia. First planted tanks where the keeper wants nutrient-rich substrate without committing to RO water or a six-week fishless cycle.",
    "sections": {
      "howItWorks": "Tropica Aquarium Soil is the European mass-market answer to ADA Amazonia. The grain is similar in size and behaves similarly but releases much less ammonia in the first weeks. The pH buffering effect is gentler, settling around 6.5 rather than 5.8. The substrate is non-uniform in grain shape, giving a more natural visual texture than the more regular ADA pellets.",
      "bestUseCases": "First planted tanks where the keeper wants nutrient-rich substrate without committing to RO water or a six-week fishless cycle. Mixed community tanks where Neocaridina shrimp share space with plants that benefit from root nutrition. Low-tech tanks where heavy ammonia release would force a fishless cycle the keeper would rather skip.",
      "commonMistakes": "Expecting Tropica to drop pH as far as Amazonia. It will not. For Caridina shrimp keepers chasing pH 5.8 to 6.5, Tropica buffers too gently and an active soil with stronger acid loading is needed.",
      "proTips": "The lower ammonia release means fish can often be added after two weeks of cycling rather than six. Pairs well with Tropica's complete fertiliser line for a single-brand workflow. The Powder variant exists at finer grain size for carpet plants."
    },
    "sources": [
      {
        "label": "Tropica Aquarium Soil product page",
        "url": "https://tropica.com/en/plants/easy/"
      },
      {
        "label": "2HR Aquarist: substrate guide",
        "url": "https://www.2hraquarist.com/blogs/substrates-overview/substrate-101"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-005",
    "slug": "tropica-aquarium-soil-powder",
    "name": "Tropica Aquarium Soil Powder",
    "brand": "Tropica",
    "category": "active-aquasoil",
    "countryOfOrigin": "Denmark",
    "colour": "Dark brown",
    "grainSize": "1 to 2 mm",
    "phTarget": "6.0 to 7.0",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Medium",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap or RO",
    "typicalPriceUsd": "$30 to $40 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "Carpet plants",
      "top dressing",
      "nano tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Same composition as standard Tropica Aquarium Soil with smaller grain (1 to 2 mm). Top layer over standard Tropica or another active soil base, or as the only substrate in a nano tank where the visual finish matters.",
    "sections": {
      "howItWorks": "Same composition as standard Tropica Aquarium Soil with smaller grain (1 to 2 mm). The smaller grain holds carpet plants more securely and produces a denser-looking substrate surface.",
      "bestUseCases": "Top layer over standard Tropica or another active soil base, or as the only substrate in a nano tank where the visual finish matters. The reduced ammonia release also makes powder type a good choice for shrimp-friendly setups.",
      "commonMistakes": "Same as ADA powder: compaction in deep layers. Use as a 1 to 2 cm cap rather than a 5 cm pure layer.",
      "proTips": "Often easier to find than ADA powder type in European and US retail. Works well as a starter substrate for keepers who want the powder grain without ADA's price."
    },
    "sources": [
      {
        "label": "Tropica Aquarium Soil Powder",
        "url": "https://tropica.com/en/plants/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-006",
    "slug": "uns-controsoil",
    "name": "UNS Controsoil",
    "brand": "Ultum Nature Systems (UNS)",
    "category": "active-aquasoil",
    "countryOfOrigin": "China (made for US market)",
    "colour": "Black (also available in brown)",
    "grainSize": "2 to 4 mm",
    "phTarget": "6.0 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "moderate",
    "nutrientContent": "High",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap or RO",
    "typicalPriceUsd": "$40 to $55 per 10L bag",
    "difficulty": 2,
    "bestFor": [
      "Mid-market high-tech planted tanks",
      "US-based aquascapers"
    ],
    "shrimpSafe": true,
    "careSummary": "UNS Controsoil is the American mid-tier active soil designed as a direct competitor to ADA Amazonia at a lower price point. Planted tank builds where ADA Amazonia is unavailable, too expensive, or considered overkill.",
    "sections": {
      "howItWorks": "UNS Controsoil is the American mid-tier active soil designed as a direct competitor to ADA Amazonia at a lower price point. The granules are slightly larger than ADA's, which makes them easier to plant into without breaking up the soil. Ammonia release is moderate, similar to Tropica, and buffering capacity is intermediate between ADA and Tropica.",
      "bestUseCases": "Planted tank builds where ADA Amazonia is unavailable, too expensive, or considered overkill. Strong choice for hobbyists running EI dosing with CO2 in a 60 to 200 litre tank. The larger grain also gives better water flow through the substrate, which reduces anaerobic-pocket risk.",
      "commonMistakes": "The bag size is 10L rather than ADA's 9L, so volume conversions need attention. Some users report that Controsoil compacts noticeably over time, especially in deeper layers.",
      "proTips": "The brown variant suits warm-tone scapes; the black variant suits the more standard dark Nature Aquarium aesthetic. Pairs well with UNS's own rimless tank line for a coordinated single-brand setup."
    },
    "sources": [
      {
        "label": "UNS Controsoil product page",
        "url": "https://ultumnaturesystems.com/products/controsoil"
      },
      {
        "label": "UKAPS: Fluval Stratum vs UNS Controsoil discussion",
        "url": "https://www.ukaps.org/forum/threads/fluval-stratum-vs-uns-controsoil.72634/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-007",
    "slug": "fluval-stratum",
    "name": "Fluval Stratum",
    "brand": "Fluval (Rolf C. Hagen)",
    "category": "active-aquasoil",
    "countryOfOrigin": "China",
    "colour": "Black to dark brown",
    "grainSize": "2 to 4 mm",
    "phTarget": "6.5 to 7.2",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "very-light",
    "nutrientContent": "Low to medium",
    "bufferingLongevity": "6 to 12 months",
    "recommendedWater": "Tap or RO",
    "typicalPriceUsd": "$25 to $40 per 10L bag",
    "difficulty": 1,
    "bestFor": [
      "First planted tank",
      "mass-market availability",
      "low-tech"
    ],
    "shrimpSafe": true,
    "careSummary": "Fluval Stratum (also known as Plant and Shrimp Stratum) uses volcanic mineral granules sourced from Japan but manufactured at scale in China. A first-time keeper's planted tank substrate in regions where ADA, Tropica, or UNS are hard to find.",
    "sections": {
      "howItWorks": "Fluval Stratum (also known as Plant and Shrimp Stratum) uses volcanic mineral granules sourced from Japan but manufactured at scale in China. The substrate releases very little ammonia, has only modest nutrient content, and lowers pH slightly. Its buffering capacity is the weakest of the active soils.",
      "bestUseCases": "A first-time keeper's planted tank substrate in regions where ADA, Tropica, or UNS are hard to find. Available in major chain stores (PetSmart, Petco, Amazon) which makes Stratum the most accessible active soil for new aquarists. Works adequately for shrimp tanks where the keeper does not need the pH locked at 5.8.",
      "commonMistakes": "Stratum is unusually lightweight and floats when first poured into water. Plants pull out easily and small carpet plants (Monte Carlo, dwarf hairgrass) struggle to grip. Stratum's buffering capacity exhausts faster than ADA or Tropica, often within a year, after which the substrate behaves like inert gravel with some residual nutrients.",
      "proTips": "Wetting Stratum before pouring it into the tank reduces the floating problem. Mixing root tabs in as the substrate is poured extends the useful nutrient life. Not a first choice for a Caridina shrimp tank or any setup that demands long-term low pH."
    },
    "sources": [
      {
        "label": "Aquarium Co-Op forum: Fluval bio-stratum comparison",
        "url": "https://forum.aquariumcoop.com/topic/32482-fluval-bio-stratum-vs-tropica-vs-neo-soil/"
      },
      {
        "label": "2HR Aquarist: substrate overview",
        "url": "https://www.2hraquarist.com/blogs/substrates-overview/substrate-101"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-008",
    "slug": "dennerle-scapers-soil",
    "name": "Dennerle Scaper's Soil",
    "brand": "Dennerle (Germany)",
    "category": "active-aquasoil",
    "countryOfOrigin": "Germany",
    "colour": "Black to very dark brown",
    "grainSize": "1 to 4 mm (irregular)",
    "phTarget": "6.0 to 6.5",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-strong",
    "ammoniaRelease": "moderate",
    "nutrientContent": "High",
    "bufferingLongevity": "12 to 24 months",
    "recommendedWater": "RO + remineraliser preferred",
    "typicalPriceUsd": "$30 to $45 per 8L bag",
    "difficulty": 3,
    "bestFor": [
      "Shrimp tanks (especially Caridina)",
      "European keepers"
    ],
    "shrimpSafe": true,
    "careSummary": "Scaper's Soil is built around Andosol, a volcanic ash soil from mountainous rainfall regions. Strong choice for Caridina shrimp tanks in Europe where Dennerle's distribution is excellent and ADA is harder to source.",
    "sections": {
      "howItWorks": "Scaper's Soil is built around Andosol, a volcanic ash soil from mountainous rainfall regions. It acts as an ion exchanger, stabilising pH at 6.0 to 6.5 and reducing KH toward zero. The substrate also has a \"nutrient buffering\" function where surplus nutrients are stored and released to plant roots as needed rather than dumping into the water column.",
      "bestUseCases": "Strong choice for Caridina shrimp tanks in Europe where Dennerle's distribution is excellent and ADA is harder to source. The Andosol mineral profile is favoured by some shrimp breeders over Amazonia for breeding-grade Crystal Red and Taiwan Bee lines.",
      "commonMistakes": "Like other active soils, treating Scaper's Soil as inert and skipping the cycling period leads to ammonia poisoning of livestock added too early. The buffering capacity holds longer than Stratum but still exhausts and requires substrate replacement at 18 to 24 months for serious shrimp setups.",
      "proTips": "The irregular grain shape (1 to 4 mm) makes for a more natural visual texture than uniform grains. Often paired with Dennerle's own root tabs and dosing line."
    },
    "sources": [
      {
        "label": "Dennerle: Scaper's Soil product page",
        "url": "https://dennerle.com/en/products/scapers-soil"
      },
      {
        "label": "Green Aqua: Dennerle Scaper's Soil 8L",
        "url": "https://greenaqua.hu/en/dennerle-scaper-s-soil-altalanos-novenytalaj-8l.html"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-009",
    "slug": "akadama",
    "name": "Akadama (DIY Japanese clay)",
    "brand": "Various (Japanese bonsai brands)",
    "category": "active-aquasoil",
    "countryOfOrigin": "Japan",
    "colour": "Tan to reddish brown",
    "grainSize": "2 to 6 mm (sold by size grade)",
    "phTarget": "6.0 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Low",
    "bufferingLongevity": "18 to 36 months",
    "recommendedWater": "RO preferred",
    "typicalPriceUsd": "$20 to $35 per 14L bag",
    "difficulty": 3,
    "bestFor": [
      "Budget-conscious shrimp keepers",
      "DIY substrate alternative"
    ],
    "shrimpSafe": true,
    "careSummary": "Akadama is a Japanese clay traditionally used in bonsai cultivation. Caridina shrimp tanks on a budget, or any planted tank where the keeper is comfortable buying from garden supply rather than aquarium retail.",
    "sections": {
      "howItWorks": "Akadama is a Japanese clay traditionally used in bonsai cultivation. The clay is processed into uniform granules with high cation exchange capacity, which lowers pH and KH similarly to manufactured aquasoils. The bonsai supply chain produces Akadama in much larger volumes than aquascaping demands, so the price per litre is much lower than purpose-built aquarium soils.",
      "bestUseCases": "Caridina shrimp tanks on a budget, or any planted tank where the keeper is comfortable buying from garden supply rather than aquarium retail. Some experienced shrimp breeders prefer Akadama specifically for its low nutrient content because it forces them to dose minerals deliberately rather than relying on substrate leaching.",
      "commonMistakes": "Garden-grade Akadama sometimes contains pesticide residue or trace contaminants. Aquarium-safe sources need to be verified before use. The granules can crumble over time, especially if disturbed during planting; gentler grades (Akadama Premium, Double Red Line) hold up longer.",
      "proTips": "Hard Akadama (the \"Double Red Line\" grade) lasts significantly longer than the softer general-grade product. Akadama also pairs well with Kanuma (another Japanese bonsai clay) for tanks that want even softer water than Akadama alone produces."
    },
    "sources": [
      {
        "label": "Wikipedia: Akadama",
        "url": "https://en.wikipedia.org/wiki/Akadama"
      },
      {
        "label": "2HR Aquarist: substrate guide",
        "url": "https://www.2hraquarist.com/blogs/substrates-overview/substrate-101"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-010",
    "slug": "caribsea-eco-complete",
    "name": "CaribSea Eco-Complete Planted",
    "brand": "CaribSea",
    "category": "inert-nutrient",
    "countryOfOrigin": "United States",
    "colour": "Black volcanic basalt",
    "grainSize": "2 to 5 mm",
    "phTarget": "Neutral (slightly buffers up)",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "Medium (pre-loaded with iron, calcium, magnesium, potassium)",
    "bufferingLongevity": "Permanent (no buffering, never exhausts)",
    "recommendedWater": "Tap or RO (any hardness)",
    "typicalPriceUsd": "$25 to $35 per 9 kg bag",
    "difficulty": 1,
    "bestFor": [
      "Hard-water keepers",
      "low-tech tanks",
      "livebearer planted tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Eco-Complete is a black volcanic basalt gravel coated with a mix of micronutrients including iron, calcium, magnesium, and potassium. Hard-water regions where active soils' pH-lowering effect would force the keeper into RO water.",
    "sections": {
      "howItWorks": "Eco-Complete is a black volcanic basalt gravel coated with a mix of micronutrients including iron, calcium, magnesium, and potassium. The substrate itself is inert and does not change water chemistry, but the coating provides slow-release nutrients to plant roots for the first year. After roughly 12 to 18 months, the coating effect diminishes and the substrate behaves like inert gravel that needs root tabs.",
      "bestUseCases": "Hard-water regions where active soils' pH-lowering effect would force the keeper into RO water. Livebearer tanks (mollies, platies, guppies) that prefer harder water and need plants that tolerate it. Low-tech tanks where heavy ammonia release would complicate cycling.",
      "commonMistakes": "Expecting Eco-Complete to drive plant growth as fast as active soil. It will not. Heavy root feeders (Amazon swords, Cryptocoryne) need supplementary root tabs after the first year. The coating washes off slightly when the substrate is rinsed too thoroughly.",
      "proTips": "Do not rinse Eco-Complete before adding to the tank. The bag's liquid contains beneficial bacteria and dissolved minerals that are intended to seed the substrate. Pour the entire contents in directly."
    },
    "sources": [
      {
        "label": "CaribSea Eco-Complete Planted product page",
        "url": "https://www.caribsea.com/freshwater-substrates/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-011",
    "slug": "seachem-flourite-black",
    "name": "Seachem Flourite Black",
    "brand": "Seachem",
    "category": "inert-nutrient",
    "countryOfOrigin": "United States",
    "colour": "Black",
    "grainSize": "1 to 2 mm (gravel)",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "Medium (iron-rich clay base)",
    "bufferingLongevity": "Permanent (never exhausts)",
    "recommendedWater": "Tap or RO (any hardness)",
    "typicalPriceUsd": "$25 to $35 per 7 kg bag",
    "difficulty": 2,
    "bestFor": [
      "Long-term planted tanks",
      "hard-water regions",
      "planted livebearer tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Flourite is a porous baked clay gravel manufactured by Seachem. Planted tanks intended to run for five-plus years without substrate replacement.",
    "sections": {
      "howItWorks": "Flourite is a porous baked clay gravel manufactured by Seachem. The substrate is naturally iron-rich and the porosity allows plant roots to grip and extract nutrients over time. Unlike active soils, Flourite does not break down or exhaust. A Flourite substrate is essentially permanent.",
      "bestUseCases": "Planted tanks intended to run for five-plus years without substrate replacement. Hard-water aquariums where active soils' pH-lowering effect would be undesirable. Tanks that mix planted scaping with fish species that need alkaline water.",
      "commonMistakes": "Flourite is notoriously dusty out of the bag. Aggressive rinsing in a bucket before adding to the tank is required, otherwise the tank stays cloudy for days. Even after rinsing, the first water change pulls some residual dust.",
      "proTips": "Mix Flourite Black with a small amount of Flourite Sand (a finer-grain variant) for a smoother visual finish. Pairs well with Seachem's complete liquid fertiliser line for a single-brand workflow."
    },
    "sources": [
      {
        "label": "Seachem Flourite Black product page",
        "url": "https://www.seachem.com/flourite-black.php"
      },
      {
        "label": "Aquarium Co-Op: Flourite review",
        "url": "https://www.aquariumcoop.com/blogs/aquarium/substrate"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-012",
    "slug": "seachem-flourite-black-sand",
    "name": "Seachem Flourite Black Sand",
    "brand": "Seachem",
    "category": "inert-nutrient",
    "countryOfOrigin": "United States",
    "colour": "Black",
    "grainSize": "0.5 to 1 mm (sand)",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "Medium (iron-rich clay base)",
    "bufferingLongevity": "Permanent",
    "recommendedWater": "Tap or RO (any hardness)",
    "typicalPriceUsd": "$30 to $40 per 7 kg bag",
    "difficulty": 2,
    "bestFor": [
      "Corydoras and bottom-dwellers",
      "smooth visual finish",
      "planted nano tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Flourite Black Sand is the fine-grain variant of standard Flourite Black. Planted tanks stocked with corydoras catfish or other barbel-bearing species.",
    "sections": {
      "howItWorks": "Flourite Black Sand is the fine-grain variant of standard Flourite Black. Same composition and behaviour, smaller grain. The finer grain protects corydoras barbels and produces a smoother visual texture, but the dust problem is amplified.",
      "bestUseCases": "Planted tanks stocked with corydoras catfish or other barbel-bearing species. Display tanks where a smooth substrate finish matters more than the maximum nutrient delivery to plant roots.",
      "commonMistakes": "Skimping on the pre-rinse. Sand-grade Flourite is much dustier than the gravel variant. Plan for at least 30 minutes of bucket rinsing before adding to the tank.",
      "proTips": "Slope the substrate front-to-back during initial setup; sand-grade substrates settle to a flat plane over time but the initial slope buys visual depth for the first six months."
    },
    "sources": [
      {
        "label": "Seachem Flourite Black Sand product page",
        "url": "https://www.seachem.com/flourite-black-sand.php"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-013",
    "slug": "pool-filter-sand",
    "name": "Pool filter sand (PFS)",
    "brand": "Various (HTH, Pavestone, generic pool supply)",
    "category": "inert-sand",
    "countryOfOrigin": "Various",
    "colour": "Tan to pale brown",
    "grainSize": "0.4 to 0.6 mm",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "None",
    "bufferingLongevity": "Permanent",
    "recommendedWater": "Any",
    "typicalPriceUsd": "$10 to $20 per 22 kg bag",
    "difficulty": 1,
    "bestFor": [
      "Budget-conscious builds",
      "corydoras tanks",
      "natural-look scapes"
    ],
    "shrimpSafe": true,
    "careSummary": "Pool filter sand is silica sand sold for swimming pool filtration. Budget planted tanks, especially with root tabs supplementing the nutrient delivery.",
    "sections": {
      "howItWorks": "Pool filter sand is silica sand sold for swimming pool filtration. The grain is uniformly sized (around 0.45 mm), pre-washed for clarity, and chemically inert. The cost per kilogram is roughly one tenth that of aquarium-branded sand.",
      "bestUseCases": "Budget planted tanks, especially with root tabs supplementing the nutrient delivery. Corydoras tanks where the soft fine grain protects barbels. Naturalistic scapes that benefit from a pale substrate.",
      "commonMistakes": "Some pool filter sand is treated with anti-algal chemicals (especially older stock) and is unsafe for aquarium use. Always check the bag and source from pool supply stores where the sand is sold as \"filter sand\" rather than \"pool sand with algaecide\".",
      "proTips": "Pre-rinse the sand thoroughly even though it is sold pre-washed. The first water column will still be cloudy for a few hours but clears within a day. Plants need root tabs every three to four months because the substrate provides no nutrients."
    },
    "sources": [
      {
        "label": "Aquarium Co-Op: substrate buying guide",
        "url": "https://www.aquariumcoop.com/blogs/aquarium/substrate"
      },
      {
        "label": "2HR Aquarist: substrate guide",
        "url": "https://www.2hraquarist.com/blogs/substrates-overview/substrate-101"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-014",
    "slug": "black-diamond-blasting-sand",
    "name": "Black Diamond Blasting Sand",
    "brand": "Black Diamond / various",
    "category": "inert-sand",
    "countryOfOrigin": "United States",
    "colour": "Black",
    "grainSize": "0.3 to 1.5 mm (sold by grit grade)",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "None",
    "bufferingLongevity": "Permanent",
    "recommendedWater": "Any",
    "typicalPriceUsd": "$10 to $15 per 22 kg bag",
    "difficulty": 2,
    "bestFor": [
      "Dark substrate on a tight budget"
    ],
    "shrimpSafe": false,
    "careSummary": "Black Diamond is coal slag, a by-product of coal-fired power generation that is sold as abrasive media for industrial sandblasting. Hobbyists who want a black substrate on a strict budget and accept the caveats.",
    "sections": {
      "howItWorks": "Black Diamond is coal slag, a by-product of coal-fired power generation that is sold as abrasive media for industrial sandblasting. The material is dark black, very cheap, and chemically resistant. Used carefully it works as aquarium substrate.",
      "bestUseCases": "Hobbyists who want a black substrate on a strict budget and accept the caveats. Coldwater tanks (white cloud mountain minnows, hillstream loaches) where the dark substrate looks striking against pale fish.",
      "commonMistakes": "",
      "proTips": "If choosing black sand on a budget, CaribSea Tahitian Moon Sand or a dedicated aquarium-grade black sand from a reputable brand is the safer alternative. The cost difference per bag is small relative to the cost of livestock that might be lost."
    },
    "sources": [
      {
        "label": "The Planted Tank Forum: Black Diamond Blasting Sand discussion",
        "url": "https://www.plantedtank.net/threads/worth-replacing-black-diamond-blasting-sand-for-seachem-flourite.1333707/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-015",
    "slug": "caribsea-tahitian-moon-sand",
    "name": "CaribSea Tahitian Moon Sand",
    "brand": "CaribSea",
    "category": "inert-sand",
    "countryOfOrigin": "United States",
    "colour": "Deep black",
    "grainSize": "0.25 to 1 mm",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "None",
    "bufferingLongevity": "Permanent",
    "recommendedWater": "Any",
    "typicalPriceUsd": "$25 to $35 per 9 kg bag",
    "difficulty": 1,
    "bestFor": [
      "Aquarium-grade black sand",
      "shrimp-safe",
      "display tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Tahitian Moon Sand is a black aragonite-free sand processed specifically for aquarium use. Display planted tanks where a clean uniform black substrate is the aesthetic goal and active soil chemistry is not needed.",
    "sections": {
      "howItWorks": "Tahitian Moon Sand is a black aragonite-free sand processed specifically for aquarium use. Unlike Black Diamond, it has been tested for shrimp and fish safety and contains no heavy metals or industrial residues. The grain is finer than aquarium gravel but slightly coarser than the finest aragonite sand.",
      "bestUseCases": "Display planted tanks where a clean uniform black substrate is the aesthetic goal and active soil chemistry is not needed. Shrimp tanks where the dark substrate makes the colours pop without any chemistry risk.",
      "commonMistakes": "Tahitian Moon Sand is finer than most gravels and can compact slightly if a deep layer is used. Keep the layer under 5 cm and stir gently during water changes to prevent anaerobic pockets.",
      "proTips": "Pairs well with white seiryu stones for a high-contrast scape. Pre-rinse to remove residual dust."
    },
    "sources": [
      {
        "label": "CaribSea Tahitian Moon Sand product page",
        "url": "https://www.caribsea.com/"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-016",
    "slug": "ada-power-sand",
    "name": "ADA Power Sand Special",
    "brand": "ADA",
    "category": "additive-or-base-layer",
    "countryOfOrigin": "Japan",
    "colour": "Pale tan with visible black additives",
    "grainSize": "5 to 10 mm (porous pumice base)",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "moderate",
    "nutrientContent": "Very high (pre-loaded with Bacter 100 and Clear Super additives)",
    "bufferingLongevity": "Functional for the substrate lifetime",
    "recommendedWater": "Used under active soil",
    "typicalPriceUsd": "$30 to $45 per 6L bag",
    "difficulty": 3,
    "bestFor": [
      "Premium ADA-style substrate stack"
    ],
    "shrimpSafe": true,
    "careSummary": "Power Sand is a base-layer substrate designed to sit under Aqua Soil. ADA-style stacked substrate (Power Sand layer of 2 to 3 cm topped with 5 to 7 cm of Aqua Soil Amazonia).",
    "sections": {
      "howItWorks": "Power Sand is a base-layer substrate designed to sit under Aqua Soil. The porous pumice grain creates water and oxygen flow channels beneath the top layer, preventing anaerobic pockets in deep substrate. The pre-loaded Bacter 100 (beneficial bacteria) and Clear Super (humic acids and trace minerals) additives release slowly through the active soil above.",
      "bestUseCases": "ADA-style stacked substrate (Power Sand layer of 2 to 3 cm topped with 5 to 7 cm of Aqua Soil Amazonia). The stack produces longer plant root systems and reduces the need for fertilisation in the first six months.",
      "commonMistakes": "Treating Power Sand as a standalone substrate. It is too porous and the additives are too concentrated for direct contact with plant roots; the active soil layer above is required.",
      "proTips": "The Special variant is for larger tanks (60 litres and up). The \"M\" size is for medium tanks. The \"S\" size is for nano tanks. Matching the size to tank volume affects flow through the base layer."
    },
    "sources": [
      {
        "label": "ADA Power Sand product page",
        "url": "https://www.adana.co.jp/en/contents/powersand/"
      },
      {
        "label": "Aquasabi: ADA Power Sand Special",
        "url": "https://www.aquasabi.com/ADA-Power-Sand-Special"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  {
    "id": "substrate-017",
    "slug": "ada-bacter-100",
    "name": "ADA Bacter 100 / Tourmaline BC",
    "brand": "ADA",
    "category": "additive-or-base-layer",
    "countryOfOrigin": "Japan",
    "colour": "Pale powder (Bacter 100), black grains (Tourmaline BC)",
    "grainSize": "Powder additives sprinkled into substrate layers",
    "phTarget": "Neutral",
    "phEffect": "neutral",
    "khEffect": "neutral",
    "ammoniaRelease": "none",
    "nutrientContent": "Beneficial bacteria and trace minerals",
    "bufferingLongevity": "Functional indefinitely once seeded",
    "recommendedWater": "Used during substrate setup",
    "typicalPriceUsd": "$20 to $40 per 100g jar",
    "difficulty": 3,
    "bestFor": [
      "ADA-style substrate stack",
      "advanced planted tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Bacter 100 is a powder of dormant beneficial bacteria that activate when the substrate is wetted. Building the full ADA premium substrate stack (Power Sand + Bacter 100 + Tourmaline BC + Aqua Soil).",
    "sections": {
      "howItWorks": "Bacter 100 is a powder of dormant beneficial bacteria that activate when the substrate is wetted. Tourmaline BC is granulated tourmaline mineral that releases trace elements (boron, sodium, potassium) into the substrate over time. Both are sprinkled in thin layers between Power Sand and Aqua Soil during substrate setup.",
      "bestUseCases": "Building the full ADA premium substrate stack (Power Sand + Bacter 100 + Tourmaline BC + Aqua Soil). Diminishing returns set in for budget-conscious tanks; the additives add real value only for high-tech high-performance setups.",
      "commonMistakes": "Sprinkling additives too thickly. The recommended dose is around one teaspoon per 60 cm of tank length, sprinkled lightly across the substrate before the next layer is added. Excess additive does not improve performance and can cloud the water column for weeks.",
      "proTips": "Skip the additives entirely on a first planted tank build. They make a measurable but small difference in already-good substrate stacks and are not the difference between success and failure."
    },
    "sources": [
      {
        "label": "ADA Bacter 100 product page",
        "url": "https://www.adana.co.jp/en/contents/aquasoil/"
      },
      {
        "label": "Aquasabi: ADA Bacter 100",
        "url": "https://www.aquasabi.com/ADA-Bacter-100"
      }
    ],
    "publishedAt": "2026-05-27T12:00:00.000Z",
    "updatedAt": "2026-05-27T12:00:00.000Z"
  },
  // ─── Added 2026-05-28: extended aquasoil coverage ────────────────────
  {
    "id": "substrate-018",
    "slug": "ada-amazonia-light",
    "name": "ADA Aqua Soil Amazonia Light Ver.2",
    "brand": "ADA",
    "category": "active-aquasoil",
    "countryOfOrigin": "Japan",
    "colour": "Dark brown",
    "grainSize": "2 to 5 mm",
    "phTarget": "6.2 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "High",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable, RO optional",
    "typicalPriceUsd": "$32 to $48 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "first planted tank",
      "Neocaridina shrimp",
      "community tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Amazonia Light Ver.2 is ADA's lighter-buffering sister to the original Amazonia. The ammonia release is roughly a third as strong and the cycle finishes in two to three weeks instead of six, so first-time aquasoil users meet less drama at startup.",
    "sections": {
      "howItWorks": "Amazonia Light uses the same Japanese black soil substrate as the original but with fewer added humic and nitrogen-rich granules. The result is a gentler initial ammonia spike, weaker pH buffering, and a substrate that is forgiving with tap water. Plants get plenty of root nutrition for the first 12 to 18 months before liquid root tabs become useful.",
      "bestUseCases": "The right choice for a first planted tank, a Neocaridina (cherry shrimp) tank where the lower buffering target matches the genus better, or any community tank where the keeper does not want to commit to RO water. It is also the ADA soil to pick when the target fish are mid-range pH species like rainbowfish or rasboras.",
      "commonMistakes": "Expecting Caridina-grade buffering. Amazonia Light does not hold pH below 6.0 reliably, so Crystal Red or Bee shrimp will struggle long-term. Treat it as a soft-water planted soil, not a Caridina shrimp soil.",
      "proTips": "A four-week fishless cycle with the tank planted and the filter running is enough to clear residual ammonia. Cap with sand only if a finer aesthetic is preferred; the substrate already looks tidy as-is."
    },
    "sources": [
      {
        "label": "ADA Aqua Soil product range",
        "url": "https://www.adana.co.jp/en/contents/aquasoil/"
      },
      {
        "label": "Aquasabi: ADA Aqua Soil Amazonia Light",
        "url": "https://www.aquasabi.com/ADA-Aqua-Soil-Amazonia-Light"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-019",
    "slug": "ada-malaya",
    "name": "ADA Aqua Soil Malaya",
    "brand": "ADA",
    "category": "active-aquasoil",
    "countryOfOrigin": "Japan",
    "colour": "Light brown to ochre",
    "grainSize": "2 to 4 mm",
    "phTarget": "6.4 to 6.9",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Medium to high",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable",
    "typicalPriceUsd": "$35 to $50 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "South-east Asian biotopes",
      "warm-toned aquascapes",
      "rasbora and gourami tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Malaya is the warm-toned member of the ADA Aqua Soil family. The colour reads ochre rather than black, which suits Southeast Asian biotopes and any aquascape where the substrate is meant to be visible rather than recede.",
    "sections": {
      "howItWorks": "Malaya is built on red-brown Indonesian volcanic clay rather than Japanese black soil. The buffering chemistry is similar to Amazonia Light, weaker than the original Amazonia, but the visual identity is completely different. Iron content is slightly higher, which deepens leaf colours on red plants like Ludwigia and Rotala.",
      "bestUseCases": "Southeast Asian biotopes featuring chocolate gouramis, harlequin rasboras, or sparkling gouramis. Also the right choice when the aquascaping intent is a warm desert or savanna palette where black soil would clash. Pairs visually with seiryu stone and spider wood.",
      "commonMistakes": "Treating Malaya as a Caridina substrate. It buffers more gently than the original Amazonia and is closer to Amazonia Light in chemistry. Caridina keepers should pick Amazonia or Africana.",
      "proTips": "Malaya tones down over the first two months as the surface dust washes off. Photograph the scape during the first week if the freshly-bagged red-brown colour is the goal."
    },
    "sources": [
      {
        "label": "ADA Aqua Soil product range",
        "url": "https://www.adana.co.jp/en/contents/aquasoil/"
      },
      {
        "label": "Aquasabi: ADA Aqua Soil Malaya",
        "url": "https://www.aquasabi.com/ADA-Aqua-Soil-Malaya"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-020",
    "slug": "landen-aquasoil",
    "name": "Landen Aquasoil",
    "brand": "Landen",
    "category": "active-aquasoil",
    "countryOfOrigin": "China",
    "colour": "Dark brown to black",
    "grainSize": "2 to 4 mm (regular), 1 to 2 mm (powder)",
    "phTarget": "6.0 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "moderate",
    "nutrientContent": "High",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable, RO optional",
    "typicalPriceUsd": "$25 to $40 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "budget-conscious planted tanks",
      "ADA-style aquascapes",
      "Neocaridina shrimp"
    ],
    "shrimpSafe": true,
    "careSummary": "Landen Aquasoil is the value option for aquascapers who want ADA-style performance without ADA pricing. The substrate is visually almost indistinguishable from Amazonia, holds shape underwater for years, and gives most planted tanks the nutrient profile they need.",
    "sections": {
      "howItWorks": "Landen uses baked clay pellets formulated to match the appearance and buffering profile of ADA Amazonia at roughly half the price. Ammonia release is moderate rather than strong, so the cycle finishes in three to four weeks. The brand sells regular and powder grain sizes alongside Akadama, Power Sand equivalents, and shrimp-specific variants.",
      "bestUseCases": "Beginner-friendly planted tanks where the keeper wants the aquasoil experience (root nutrition, soft-water buffering, fine grain) without the ADA price tag. Also a popular choice for builders running multiple tanks who do not want to stack six ADA bags per build.",
      "commonMistakes": "Assuming Landen is inferior to Amazonia. Side-by-side tests on aquascaping forums consistently show comparable plant growth in the first six months. The difference shows up in longevity, Landen typically exhausts buffering at the 12 to 18 month mark while premium Amazonia holds buffering closer to 24 months.",
      "proTips": "Landen aquasoil pellets are slightly softer than Amazonia. Avoid vigorous gravel-vac sessions, the surface will pulverise. Use a turkey baster or light siphon instead."
    },
    "sources": [
      {
        "label": "Landen Aquatics official",
        "url": "https://landenaquatics.com/"
      },
      {
        "label": "Buceplant: Landen Aquasoil",
        "url": "https://buceplant.com/products/landen-aqua-soil"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-021",
    "slug": "mr-aqua-aquasoil",
    "name": "Mr. Aqua Aquasoil",
    "brand": "Mr. Aqua",
    "category": "active-aquasoil",
    "countryOfOrigin": "Taiwan",
    "colour": "Dark brown",
    "grainSize": "1 to 3 mm",
    "phTarget": "6.4 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Medium",
    "bufferingLongevity": "10 to 15 months",
    "recommendedWater": "Tap water tolerable",
    "typicalPriceUsd": "$22 to $35 per 8L bag",
    "difficulty": 2,
    "bestFor": [
      "nano tanks",
      "rimless cube scapes",
      "first-time aquasoil users"
    ],
    "shrimpSafe": true,
    "careSummary": "Mr. Aqua's aquasoil is the nano-tank specialist of the group. The grain is smaller than most aquasoils, which means it tucks into tight scapes around stone and wood without looking chunky. Buffering is mild, ammonia release is light.",
    "sections": {
      "howItWorks": "Mr. Aqua's aquasoil is a Taiwanese-manufactured baked clay product with a slightly finer grain than ADA Amazonia. Ammonia release is light rather than strong, so the substrate cycles in two to three weeks. Buffering is mild enough that tap water with moderate hardness still settles into the target range.",
      "bestUseCases": "Nano tanks (5 to 30 litres), rimless cubes, and any scape where a fine, uniform substrate is the visual goal. Mr. Aqua is also a common choice for first-time aquasoil users in shrimp tanks because the ammonia spike is mild enough to skip the long cycle.",
      "commonMistakes": "Buying for a high-tech 200 litre tank. The nutrient content is medium and the buffering is mild, so a large CO2-injected setup will exhaust the substrate inside a year and need root tabs.",
      "proTips": "The bag includes a thin layer of large pellets at the top, sort or stir before filling so the grain is uniform. Lift Mr. Aqua's bag from the bottom when pouring, the fine grain settles and the top of the bag is mostly pellet skin."
    },
    "sources": [
      {
        "label": "Mr. Aqua products",
        "url": "https://mraqua.com/"
      },
      {
        "label": "AquaCave: Mr. Aqua Soil",
        "url": "https://www.aquacave.com/mr-aqua-soil"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-022",
    "slug": "jbl-proscape-plantsoil",
    "name": "JBL ProScape PlantSoil",
    "brand": "JBL",
    "category": "active-aquasoil",
    "countryOfOrigin": "Germany",
    "colour": "Dark brown to black",
    "grainSize": "2 to 4 mm",
    "phTarget": "6.5 to 7.0",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "very-light",
    "nutrientContent": "Medium to high",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable",
    "typicalPriceUsd": "$30 to $45 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "European tap-water builds",
      "low-tech planted tanks",
      "fish-in cycling"
    ],
    "shrimpSafe": true,
    "careSummary": "JBL's PlantSoil is the German-engineered take on the aquasoil category. The brand emphasises minimal ammonia release at startup, so tanks can be planted, filled, and stocked within a couple of weeks rather than cycled for two months.",
    "sections": {
      "howItWorks": "PlantSoil is a baked clay aquasoil engineered for very low ammonia release at startup. JBL formulates it so the substrate's nutrient release favours iron and macronutrients over nitrogen, which means plants grow well without seeding the water column with ammonia. The substrate is sold in both 'PlantSoil Brown' and 'PlantSoil Black' colour variants.",
      "bestUseCases": "European tap-water builds where carbonate hardness is moderate (KH 4 to 8) and the keeper does not want to commit to RO. Also a good choice for low-tech tanks running stem plants on liquid carbon, since the substrate provides root nutrition without driving extreme acidity.",
      "commonMistakes": "Expecting the deep Caridina buffering of ADA Amazonia. PlantSoil is mild by design. If the target is pH 5.8 to 6.2 for Crystal Red shrimp, Amazonia or Africana is the right pick.",
      "proTips": "The substrate can be planted and lightly stocked from week two onward. JBL's own dosing line (ProScape Macro, Micro, Fe) is formulated to complement the substrate's nutrient release."
    },
    "sources": [
      {
        "label": "JBL ProScape PlantSoil product page",
        "url": "https://www.jbl.de/en/products/detail/5856/jbl-proscape-plantsoil-brown"
      },
      {
        "label": "Aquasabi: JBL ProScape PlantSoil",
        "url": "https://www.aquasabi.com/JBL-ProScape-PlantSoil"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-023",
    "slug": "oliver-knott-nature-soil",
    "name": "Oliver Knott Nature Soil",
    "brand": "Oliver Knott",
    "category": "active-aquasoil",
    "countryOfOrigin": "Germany",
    "colour": "Black to dark brown",
    "grainSize": "1 to 3 mm",
    "phTarget": "6.2 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "High",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable, RO optional",
    "typicalPriceUsd": "$28 to $42 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "aquascaping competitions",
      "fine-grain detail work",
      "rimless display tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "Oliver Knott Nature Soil is a designer aquasoil with a noticeably finer grain than most competitors. It is associated with European aquascaping competition entries because the small grain reads well in photographs and tucks neatly around hardscape detail.",
    "sections": {
      "howItWorks": "Designed by German aquascaper Oliver Knott, the substrate is a baked clay aquasoil with grain selected to be finer and more uniform than most competitors. Buffering is mild, ammonia release is light, and the substrate holds shape underwater for over a year. The brand also sells a powder variant labelled Smart Soil.",
      "bestUseCases": "Aquascaping competition entries where the substrate must read cleanly in photographs. Rimless display tanks where the fine grain elevates the scape's perceived quality. Also a popular choice for foreground carpets like Monte Carlo or HC Cuba because the fine grain holds runners well.",
      "commonMistakes": "Pouring the substrate from a height, the fine grain dusts the tank glass and takes a week to settle. Pour close to the substrate floor with a scoop.",
      "proTips": "Mix with Oliver Knott Substrate Conditioner during setup for an extra root nutrition boost. The pellets are slightly softer than Amazonia, so avoid heavy gravel-vac sessions."
    },
    "sources": [
      {
        "label": "Oliver Knott products at Aqua Rebell",
        "url": "https://www.aqua-rebell.de/Oliver-Knott"
      },
      {
        "label": "Aquasabi: Oliver Knott Nature Soil",
        "url": "https://www.aquasabi.com/Oliver-Knott-Nature-Soil"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-024",
    "slug": "brightwell-florinvolcanit",
    "name": "Brightwell FlorinVolcanit",
    "brand": "Brightwell Aquatics",
    "category": "active-aquasoil",
    "countryOfOrigin": "United States",
    "colour": "Dark brown to charcoal",
    "grainSize": "1 to 4 mm",
    "phTarget": "6.4 to 7.0",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Medium to high",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable",
    "typicalPriceUsd": "$32 to $48 per 8L bag",
    "difficulty": 3,
    "bestFor": [
      "Brightwell dosing systems",
      "North American tap water",
      "low-tech planted tanks"
    ],
    "shrimpSafe": true,
    "careSummary": "FlorinVolcanit is Brightwell's planted-tank substrate, a baked volcanic clay product engineered to release a balanced mix of macro and micronutrients. It pairs naturally with Brightwell's broader FlorinMulti dosing line.",
    "sections": {
      "howItWorks": "FlorinVolcanit is a baked volcanic clay product engineered to release a slow, balanced mix of macro and micronutrients. The substrate has high cation exchange capacity, which means it stores fertiliser dosed into the water column and releases it back to plant roots as needed. The buffering profile is mild.",
      "bestUseCases": "Tanks dosed with Brightwell's FlorinMulti, FlorinPotassium, and FlorinAxis line. Also a strong choice in North American hard-water regions where moderate buffering is enough to bring the tank into the planted-tank range without RO. Pairs well with low-tech to mid-tech planted setups.",
      "commonMistakes": "Mixing FlorinVolcanit with another aquasoil. The chemistry is engineered for the Brightwell dosing system, blending it dilutes both substrates.",
      "proTips": "Brightwell publishes detailed dosing calculators that account for tank size, plant load, and substrate volume. Use them rather than guessing at fertiliser amounts."
    },
    "sources": [
      {
        "label": "Brightwell Aquatics: FlorinVolcanit",
        "url": "https://www.brightwellaquatics.com/products/florinvolcanit.php"
      },
      {
        "label": "Aquarium Co-Op: Brightwell FlorinVolcanit",
        "url": "https://www.aquariumcoop.com/products/florinvolcanit"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-025",
    "slug": "aquario-neo-soil",
    "name": "Aquario Neo Soil for Plant",
    "brand": "Aquario",
    "category": "active-aquasoil",
    "countryOfOrigin": "South Korea",
    "colour": "Dark brown",
    "grainSize": "2 to 4 mm",
    "phTarget": "6.0 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "moderate",
    "nutrientContent": "High",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable, RO optional",
    "typicalPriceUsd": "$28 to $42 per 8L bag",
    "difficulty": 2,
    "bestFor": [
      "Neocaridina shrimp",
      "stem-plant heavy scapes",
      "iwagumi layouts"
    ],
    "shrimpSafe": true,
    "careSummary": "Aquario's Neo Soil for Plant is a Korean-manufactured aquasoil that has built a strong reputation among Asian aquascapers. The substrate cycles in three to four weeks and offers strong root nutrition for stem plants and carpeting species.",
    "sections": {
      "howItWorks": "Aquario's Neo Soil for Plant is a baked black clay aquasoil. Aquario also sells Neo Soil for Shrimp, which uses the same base with stronger buffering and lower nutrient release for Caridina tanks. The substrate has noticeably high iron content, which encourages deep red colouration on Ludwigia and Rotala.",
      "bestUseCases": "Stem-plant heavy aquascapes where the substrate is mostly hidden under foliage anyway, and the priority is root nutrition. Aquario's own Co Tropica grass and stem-plant tissue cultures pair naturally with the substrate. Iwagumi layouts with hairgrass carpets also work well.",
      "commonMistakes": "Buying the wrong variant. Neo Soil for Plant is for planted tanks, Neo Soil for Shrimp is for Caridina. Mixing them up is a common returns reason.",
      "proTips": "The substrate is slightly more buoyant than ADA Amazonia for the first 24 hours, dust the surface lightly with water before filling to keep pellets in place."
    },
    "sources": [
      {
        "label": "Aquario Neo Plant Soil",
        "url": "https://aquario.life/products/aquario-neo-soil-plant"
      },
      {
        "label": "Buceplant: Aquario Neo Soil",
        "url": "https://buceplant.com/products/aquario-neo-soil-plant"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-026",
    "slug": "prodibio-aquagrowth-soil",
    "name": "Prodibio AquaGrowth Soil",
    "brand": "Prodibio",
    "category": "active-aquasoil",
    "countryOfOrigin": "France",
    "colour": "Dark brown",
    "grainSize": "2 to 3 mm",
    "phTarget": "6.5 to 7.0",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "very-light",
    "nutrientContent": "Medium",
    "bufferingLongevity": "10 to 14 months",
    "recommendedWater": "Tap water tolerable",
    "typicalPriceUsd": "$30 to $44 per 9L bag",
    "difficulty": 2,
    "bestFor": [
      "Prodibio bacterial dosing systems",
      "fish-first planted tanks",
      "low-maintenance scapes"
    ],
    "shrimpSafe": true,
    "careSummary": "Prodibio's AquaGrowth Soil is engineered to pair with the brand's BioDigest bacterial dosing system. The substrate releases almost no ammonia at startup, so the tank can carry fish and shrimp from week two onward.",
    "sections": {
      "howItWorks": "AquaGrowth Soil is a baked clay aquasoil designed for Prodibio's bacterial dosing system. The substrate is pre-conditioned with beneficial bacteria, which means ammonia release at startup is minimal and the tank is ready for livestock within two weeks of setup if BioDigest ampoules are added. Buffering is mild.",
      "bestUseCases": "Tanks running Prodibio's full dosing line (BioDigest, Stop Ammo, AquaGrowth Fert). Fish-first planted tanks where the goal is to stock fish quickly after setup. Also a strong choice for low-maintenance scapes that the keeper wants to dose monthly rather than weekly.",
      "commonMistakes": "Skipping the BioDigest dosing. The substrate is engineered to work with the bacterial system, without it the substrate is just a mild aquasoil and the value proposition disappears.",
      "proTips": "Prodibio ampoules dose by tank volume, not substrate volume. Calculate based on net water volume after rocks and wood displace it."
    },
    "sources": [
      {
        "label": "Prodibio AquaGrowth Soil",
        "url": "https://www.prodibio.com/en/our-products/aquagrowth-soil/"
      },
      {
        "label": "Aquasabi: Prodibio AquaGrowth Soil",
        "url": "https://www.aquasabi.com/Prodibio-AquaGrowth-Soil"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
  {
    "id": "substrate-027",
    "slug": "help-advanced-soil",
    "name": "Help Advanced Soil",
    "brand": "Aquatic Nature",
    "category": "active-aquasoil",
    "countryOfOrigin": "Belgium",
    "colour": "Dark brown to black",
    "grainSize": "2 to 4 mm",
    "phTarget": "6.0 to 6.8",
    "phEffect": "lowers-gentle",
    "khEffect": "lowers-gentle",
    "ammoniaRelease": "light",
    "nutrientContent": "Medium to high",
    "bufferingLongevity": "12 to 18 months",
    "recommendedWater": "Tap water tolerable, RO optional",
    "typicalPriceUsd": "$26 to $40 per 8L bag",
    "difficulty": 2,
    "bestFor": [
      "European builders",
      "Neocaridina shrimp",
      "low to mid-tech planted"
    ],
    "shrimpSafe": true,
    "careSummary": "Aquatic Nature's Help Advanced Soil is the Belgian brand's planted-tank substrate. It runs at a similar price point to JBL PlantSoil and Tropica Aquarium Soil, with comparable performance.",
    "sections": {
      "howItWorks": "Help Advanced Soil is Aquatic Nature's contribution to the active aquasoil category. Baked clay pellets release a balanced macro/micronutrient profile and mild buffering. Available in two variants, Plus (higher nutrient content for planted tanks) and Shrimp (stronger buffering for Caridina).",
      "bestUseCases": "European builders sourcing through local fish shops where Aquatic Nature has strong distribution. Neocaridina shrimp tanks at the Plus variant, Caridina tanks at the Shrimp variant. Low to mid-tech planted setups running liquid CO2 or pressurised injection at the lower end.",
      "commonMistakes": "Mixing variants in one substrate bed. Plus and Shrimp variants have different buffering targets, blending them creates a mid-range pH that satisfies neither plants nor shrimp optimally.",
      "proTips": "The substrate pairs naturally with Aquatic Nature's own dosing line. Their starter kits bundle substrate, dosing, and bacterial conditioner at a discount versus buying separately."
    },
    "sources": [
      {
        "label": "Aquatic Nature: Help Advanced Soil",
        "url": "https://www.aquatic-nature.be/en/products/help-advanced-soil/"
      },
      {
        "label": "Aquasabi: Aquatic Nature Help Advanced Soil",
        "url": "https://www.aquasabi.com/Aquatic-Nature-Help-Advanced-Soil"
      }
    ],
    "publishedAt": "2026-05-28T12:00:00.000Z",
    "updatedAt": "2026-05-28T12:00:00.000Z"
  },
];

export function findSubstrate(slug: string): SubstrateEntry | undefined {
  return substrates.find((s) => s.slug === slug);
}
